<?php

declare(strict_types=1);

namespace App\Http\Controllers\Tools;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Inertia\Inertia;
use Inertia\Response;

/**
 * ShippingAnalysisController — Shipping cost by country analysis tool.
 *
 * Returns the Tools/ShippingAnalysis/Index Inertia page with mock per-country
 * shipping economics: carrier cost vs charged, return rate, COD penetration,
 * contribution margin. No DB queries — all data is static mock until the
 * ShippingAnalysisService layer is built.
 *
 * Reads:  nothing (mock data stub)
 * Writes: nothing
 * Called by: GET /{workspace:slug}/tools/shipping-analysis
 *
 * @see docs/competitors/_research_shipping_country_analysis.md
 * @see docs/pages/settings.md §settings/costs — rule definition (this page = analysis)
 * @see docs/pages/profit.md   §BarChart "Profit by Country" — sibling surface
 * @see docs/UX.md §5 shared primitives (DataTable, DrawerSidePanel, MetricCardCompact)
 */
class ShippingAnalysisController extends Controller
{
    public function __invoke(Request $request): Response
    {
        $validated = $request->validate([
            'from'   => ['sometimes', 'nullable', 'date_format:Y-m-d'],
            'to'     => ['sometimes', 'nullable', 'date_format:Y-m-d', 'after_or_equal:from'],
            'region' => ['sometimes', 'nullable', 'string', 'max:32'],
            'status' => ['sometimes', 'nullable', 'in:profitable,marginal,loss'],
            'min_orders' => ['sometimes', 'nullable', 'integer', 'min:0'],
        ]);

        $from     = $validated['from']      ?? now()->subDays(29)->toDateString();
        $to       = $validated['to']        ?? now()->toDateString();
        $region   = $validated['region']    ?? null;
        $status   = $validated['status']    ?? null;
        $minOrders = $validated['min_orders'] ?? 0;

        return Inertia::render('Tools/ShippingAnalysis/Index', [
            'countries'  => self::mockCountries(),
            'summary'    => self::mockSummary(),
            'filters'    => [
                'from'       => $from,
                'to'         => $to,
                'region'     => $region,
                'status'     => $status,
                'min_orders' => $minOrders,
            ],
        ]);
    }

    /**
     * 50-country mock dataset.
     *
     * Columns match the research spec:
     *   country_code, country_name, region, orders, revenue,
     *   avg_shipping_charged, avg_carrier_cost, returns, return_pct,
     *   cod_pct, cod_cost_per_order, avg_speed_days,
     *   contribution_margin, contribution_margin_pct, status
     *
     * Distribution notes:
     *   - US/UK/CA/AU/DE/FR/NL — dominant volumes
     *   - IT/GR/RO/PL/TR/BG/RS — high COD penetration (>30%)
     *   - Remote islands (FJ/PF/SB/WS) — Loss status (high carrier cost)
     *   - Avg shipping cost $4–$45 by distance/weight zone
     *   - Returns 0.5–18% by country (DE highest; JP/SG lowest)
     *
     * @return array<int, array<string, mixed>>
     */
    private static function mockCountries(): array
    {
        return [
            // ── Tier 1: Dominant markets ─────────────────────────────────────
            [
                'country_code'              => 'US',
                'country_name'              => 'United States',
                'region'                    => 'Americas',
                'orders'                    => 4820,
                'revenue'                   => 289_200,
                'avg_shipping_charged'      => 6.50,
                'avg_carrier_cost'          => 5.80,
                'returns'                   => 337,
                'return_pct'                => 6.99,
                'cod_pct'                   => 0.0,
                'cod_cost_per_order'        => 0.0,
                'avg_speed_days'            => 3.2,
                'contribution_margin'       => 92_800,
                'contribution_margin_pct'   => 32.1,
                'status'                    => 'profitable',
                'detail'                    => self::mockDetail('US'),
            ],
            [
                'country_code'              => 'GB',
                'country_name'              => 'United Kingdom',
                'region'                    => 'Europe',
                'orders'                    => 1_940,
                'revenue'                   => 108_400,
                'avg_shipping_charged'      => 7.20,
                'avg_carrier_cost'          => 7.80,
                'returns'                   => 214,
                'return_pct'                => 11.03,
                'cod_pct'                   => 0.0,
                'cod_cost_per_order'        => 0.0,
                'avg_speed_days'            => 4.1,
                'contribution_margin'       => 31_400,
                'contribution_margin_pct'   => 28.97,
                'status'                    => 'profitable',
                'detail'                    => self::mockDetail('GB'),
            ],
            [
                'country_code'              => 'CA',
                'country_name'              => 'Canada',
                'region'                    => 'Americas',
                'orders'                    => 1_210,
                'revenue'                   => 64_300,
                'avg_shipping_charged'      => 9.40,
                'avg_carrier_cost'          => 9.10,
                'returns'                   => 97,
                'return_pct'                => 8.02,
                'cod_pct'                   => 0.0,
                'cod_cost_per_order'        => 0.0,
                'avg_speed_days'            => 5.3,
                'contribution_margin'       => 18_600,
                'contribution_margin_pct'   => 28.93,
                'status'                    => 'profitable',
                'detail'                    => self::mockDetail('CA'),
            ],
            [
                'country_code'              => 'AU',
                'country_name'              => 'Australia',
                'region'                    => 'Asia Pacific',
                'orders'                    => 920,
                'revenue'                   => 51_800,
                'avg_shipping_charged'      => 12.00,
                'avg_carrier_cost'          => 11.40,
                'returns'                   => 65,
                'return_pct'                => 7.07,
                'cod_pct'                   => 0.0,
                'cod_cost_per_order'        => 0.0,
                'avg_speed_days'            => 7.2,
                'contribution_margin'       => 14_900,
                'contribution_margin_pct'   => 28.76,
                'status'                    => 'profitable',
                'detail'                    => self::mockDetail('AU'),
            ],
            [
                'country_code'              => 'DE',
                'country_name'              => 'Germany',
                'region'                    => 'Europe',
                'orders'                    => 1_640,
                'revenue'                   => 88_600,
                'avg_shipping_charged'      => 5.90,
                'avg_carrier_cost'          => 6.40,
                'returns'                   => 295,
                'return_pct'                => 17.99,
                'cod_pct'                   => 4.2,
                'cod_cost_per_order'        => 2.20,
                'avg_speed_days'            => 2.8,
                'contribution_margin'       => 19_400,
                'contribution_margin_pct'   => 21.9,
                'status'                    => 'profitable',
                'detail'                    => self::mockDetail('DE'),
            ],
            [
                'country_code'              => 'FR',
                'country_name'              => 'France',
                'region'                    => 'Europe',
                'orders'                    => 980,
                'revenue'                   => 52_400,
                'avg_shipping_charged'      => 6.10,
                'avg_carrier_cost'          => 6.60,
                'returns'                   => 118,
                'return_pct'                => 12.04,
                'cod_pct'                   => 2.1,
                'cod_cost_per_order'        => 1.80,
                'avg_speed_days'            => 3.6,
                'contribution_margin'       => 12_100,
                'contribution_margin_pct'   => 23.09,
                'status'                    => 'profitable',
                'detail'                    => self::mockDetail('FR'),
            ],
            [
                'country_code'              => 'NL',
                'country_name'              => 'Netherlands',
                'region'                    => 'Europe',
                'orders'                    => 620,
                'revenue'                   => 34_100,
                'avg_shipping_charged'      => 5.50,
                'avg_carrier_cost'          => 5.90,
                'returns'                   => 87,
                'return_pct'                => 14.03,
                'cod_pct'                   => 1.3,
                'cod_cost_per_order'        => 1.50,
                'avg_speed_days'            => 2.4,
                'contribution_margin'       => 8_200,
                'contribution_margin_pct'   => 24.05,
                'status'                    => 'profitable',
                'detail'                    => self::mockDetail('NL'),
            ],

            // ── Tier 2: Strong secondary markets ─────────────────────────────
            [
                'country_code'              => 'SE',
                'country_name'              => 'Sweden',
                'region'                    => 'Europe',
                'orders'                    => 480,
                'revenue'                   => 27_200,
                'avg_shipping_charged'      => 7.00,
                'avg_carrier_cost'          => 7.40,
                'returns'                   => 62,
                'return_pct'                => 12.92,
                'cod_pct'                   => 0.5,
                'cod_cost_per_order'        => 1.20,
                'avg_speed_days'            => 4.0,
                'contribution_margin'       => 6_200,
                'contribution_margin_pct'   => 22.79,
                'status'                    => 'profitable',
                'detail'                    => self::mockDetail('SE'),
            ],
            [
                'country_code'              => 'NO',
                'country_name'              => 'Norway',
                'region'                    => 'Europe',
                'orders'                    => 310,
                'revenue'                   => 18_600,
                'avg_shipping_charged'      => 8.50,
                'avg_carrier_cost'          => 9.20,
                'returns'                   => 34,
                'return_pct'                => 10.97,
                'cod_pct'                   => 0.3,
                'cod_cost_per_order'        => 1.20,
                'avg_speed_days'            => 5.1,
                'contribution_margin'       => 3_900,
                'contribution_margin_pct'   => 20.97,
                'status'                    => 'profitable',
                'detail'                    => self::mockDetail('NO'),
            ],
            [
                'country_code'              => 'DK',
                'country_name'              => 'Denmark',
                'region'                    => 'Europe',
                'orders'                    => 240,
                'revenue'                   => 13_900,
                'avg_shipping_charged'      => 6.80,
                'avg_carrier_cost'          => 7.10,
                'returns'                   => 31,
                'return_pct'                => 12.92,
                'cod_pct'                   => 0.4,
                'cod_cost_per_order'        => 1.20,
                'avg_speed_days'            => 3.5,
                'contribution_margin'       => 3_200,
                'contribution_margin_pct'   => 23.02,
                'status'                    => 'profitable',
                'detail'                    => self::mockDetail('DK'),
            ],
            [
                'country_code'              => 'CH',
                'country_name'              => 'Switzerland',
                'region'                    => 'Europe',
                'orders'                    => 290,
                'revenue'                   => 19_800,
                'avg_shipping_charged'      => 9.00,
                'avg_carrier_cost'          => 10.50,
                'returns'                   => 26,
                'return_pct'                => 8.97,
                'cod_pct'                   => 2.8,
                'cod_cost_per_order'        => 2.80,
                'avg_speed_days'            => 4.8,
                'contribution_margin'       => 3_400,
                'contribution_margin_pct'   => 17.17,
                'status'                    => 'profitable',
                'detail'                    => self::mockDetail('CH'),
            ],
            [
                'country_code'              => 'AT',
                'country_name'              => 'Austria',
                'region'                    => 'Europe',
                'orders'                    => 210,
                'revenue'                   => 11_400,
                'avg_shipping_charged'      => 6.20,
                'avg_carrier_cost'          => 6.80,
                'returns'                   => 32,
                'return_pct'                => 15.24,
                'cod_pct'                   => 8.1,
                'cod_cost_per_order'        => 2.40,
                'avg_speed_days'            => 3.2,
                'contribution_margin'       => 2_300,
                'contribution_margin_pct'   => 20.18,
                'status'                    => 'profitable',
                'detail'                    => self::mockDetail('AT'),
            ],
            [
                'country_code'              => 'ES',
                'country_name'              => 'Spain',
                'region'                    => 'Europe',
                'orders'                    => 540,
                'revenue'                   => 27_800,
                'avg_shipping_charged'      => 6.40,
                'avg_carrier_cost'          => 7.10,
                'returns'                   => 73,
                'return_pct'                => 13.52,
                'cod_pct'                   => 6.4,
                'cod_cost_per_order'        => 2.10,
                'avg_speed_days'            => 4.9,
                'contribution_margin'       => 5_900,
                'contribution_margin_pct'   => 21.22,
                'status'                    => 'profitable',
                'detail'                    => self::mockDetail('ES'),
            ],
            [
                'country_code'              => 'JP',
                'country_name'              => 'Japan',
                'region'                    => 'Asia Pacific',
                'orders'                    => 390,
                'revenue'                   => 23_400,
                'avg_shipping_charged'      => 14.00,
                'avg_carrier_cost'          => 13.20,
                'returns'                   => 8,
                'return_pct'                => 2.05,
                'cod_pct'                   => 18.4,
                'cod_cost_per_order'        => 3.50,
                'avg_speed_days'            => 6.8,
                'contribution_margin'       => 5_200,
                'contribution_margin_pct'   => 22.22,
                'status'                    => 'profitable',
                'detail'                    => self::mockDetail('JP'),
            ],
            [
                'country_code'              => 'SG',
                'country_name'              => 'Singapore',
                'region'                    => 'Asia Pacific',
                'orders'                    => 280,
                'revenue'                   => 17_200,
                'avg_shipping_charged'      => 11.50,
                'avg_carrier_cost'          => 10.80,
                'returns'                   => 6,
                'return_pct'                => 2.14,
                'cod_pct'                   => 0.0,
                'cod_cost_per_order'        => 0.0,
                'avg_speed_days'            => 7.4,
                'contribution_margin'       => 4_100,
                'contribution_margin_pct'   => 23.84,
                'status'                    => 'profitable',
                'detail'                    => self::mockDetail('SG'),
            ],
            [
                'country_code'              => 'NZ',
                'country_name'              => 'New Zealand',
                'region'                    => 'Asia Pacific',
                'orders'                    => 190,
                'revenue'                   => 10_800,
                'avg_shipping_charged'      => 13.50,
                'avg_carrier_cost'          => 13.90,
                'returns'                   => 15,
                'return_pct'                => 7.89,
                'cod_pct'                   => 0.0,
                'cod_cost_per_order'        => 0.0,
                'avg_speed_days'            => 9.1,
                'contribution_margin'       => 1_800,
                'contribution_margin_pct'   => 16.67,
                'status'                    => 'profitable',
                'detail'                    => self::mockDetail('NZ'),
            ],

            // ── COD-heavy markets ─────────────────────────────────────────────
            [
                'country_code'              => 'IT',
                'country_name'              => 'Italy',
                'region'                    => 'Europe',
                'orders'                    => 680,
                'revenue'                   => 34_600,
                'avg_shipping_charged'      => 6.80,
                'avg_carrier_cost'          => 8.20,
                'returns'                   => 102,
                'return_pct'                => 15.0,
                'cod_pct'                   => 42.3,
                'cod_cost_per_order'        => 3.20,
                'avg_speed_days'            => 5.4,
                'contribution_margin'       => 4_900,
                'contribution_margin_pct'   => 14.16,
                'status'                    => 'marginal',
                'detail'                    => self::mockDetail('IT'),
            ],
            [
                'country_code'              => 'GR',
                'country_name'              => 'Greece',
                'region'                    => 'Europe',
                'orders'                    => 320,
                'revenue'                   => 15_200,
                'avg_shipping_charged'      => 7.50,
                'avg_carrier_cost'          => 9.80,
                'returns'                   => 61,
                'return_pct'                => 19.06,
                'cod_pct'                   => 58.7,
                'cod_cost_per_order'        => 3.80,
                'avg_speed_days'            => 6.2,
                'contribution_margin'       => 1_400,
                'contribution_margin_pct'   => 9.21,
                'status'                    => 'marginal',
                'detail'                    => self::mockDetail('GR'),
            ],
            [
                'country_code'              => 'RO',
                'country_name'              => 'Romania',
                'region'                    => 'Europe',
                'orders'                    => 410,
                'revenue'                   => 17_800,
                'avg_shipping_charged'      => 4.20,
                'avg_carrier_cost'          => 6.10,
                'returns'                   => 98,
                'return_pct'                => 23.9,
                'cod_pct'                   => 64.1,
                'cod_cost_per_order'        => 2.90,
                'avg_speed_days'            => 5.8,
                'contribution_margin'       => -800,
                'contribution_margin_pct'   => -4.49,
                'status'                    => 'loss',
                'detail'                    => self::mockDetail('RO'),
            ],
            [
                'country_code'              => 'PL',
                'country_name'              => 'Poland',
                'region'                    => 'Europe',
                'orders'                    => 520,
                'revenue'                   => 22_400,
                'avg_shipping_charged'      => 4.80,
                'avg_carrier_cost'          => 5.90,
                'returns'                   => 114,
                'return_pct'                => 21.92,
                'cod_pct'                   => 35.8,
                'cod_cost_per_order'        => 2.60,
                'avg_speed_days'            => 4.4,
                'contribution_margin'       => 1_200,
                'contribution_margin_pct'   => 5.36,
                'status'                    => 'marginal',
                'detail'                    => self::mockDetail('PL'),
            ],
            [
                'country_code'              => 'TR',
                'country_name'              => 'Turkey',
                'region'                    => 'Europe',
                'orders'                    => 290,
                'revenue'                   => 11_600,
                'avg_shipping_charged'      => 4.00,
                'avg_carrier_cost'          => 7.20,
                'returns'                   => 87,
                'return_pct'                => 30.0,
                'cod_pct'                   => 61.4,
                'cod_cost_per_order'        => 3.40,
                'avg_speed_days'            => 7.1,
                'contribution_margin'       => -2_100,
                'contribution_margin_pct'   => -18.1,
                'status'                    => 'loss',
                'detail'                    => self::mockDetail('TR'),
            ],
            [
                'country_code'              => 'BG',
                'country_name'              => 'Bulgaria',
                'region'                    => 'Europe',
                'orders'                    => 180,
                'revenue'                   => 7_200,
                'avg_shipping_charged'      => 3.80,
                'avg_carrier_cost'          => 5.80,
                'returns'                   => 54,
                'return_pct'                => 30.0,
                'cod_pct'                   => 72.2,
                'cod_cost_per_order'        => 2.80,
                'avg_speed_days'            => 5.6,
                'contribution_margin'       => -900,
                'contribution_margin_pct'   => -12.5,
                'status'                    => 'loss',
                'detail'                    => self::mockDetail('BG'),
            ],
            [
                'country_code'              => 'RS',
                'country_name'              => 'Serbia',
                'region'                    => 'Europe',
                'orders'                    => 140,
                'revenue'                   => 5_600,
                'avg_shipping_charged'      => 4.10,
                'avg_carrier_cost'          => 6.50,
                'returns'                   => 42,
                'return_pct'                => 30.0,
                'cod_pct'                   => 68.6,
                'cod_cost_per_order'        => 2.70,
                'avg_speed_days'            => 6.8,
                'contribution_margin'       => -600,
                'contribution_margin_pct'   => -10.71,
                'status'                    => 'loss',
                'detail'                    => self::mockDetail('RS'),
            ],

            // ── Tier 3: Mid-volume markets ────────────────────────────────────
            [
                'country_code'              => 'BE',
                'country_name'              => 'Belgium',
                'region'                    => 'Europe',
                'orders'                    => 310,
                'revenue'                   => 17_100,
                'avg_shipping_charged'      => 5.80,
                'avg_carrier_cost'          => 6.20,
                'returns'                   => 43,
                'return_pct'                => 13.87,
                'cod_pct'                   => 1.6,
                'cod_cost_per_order'        => 1.60,
                'avg_speed_days'            => 2.9,
                'contribution_margin'       => 3_900,
                'contribution_margin_pct'   => 22.81,
                'status'                    => 'profitable',
                'detail'                    => self::mockDetail('BE'),
            ],
            [
                'country_code'              => 'FI',
                'country_name'              => 'Finland',
                'region'                    => 'Europe',
                'orders'                    => 170,
                'revenue'                   => 9_800,
                'avg_shipping_charged'      => 7.40,
                'avg_carrier_cost'          => 7.80,
                'returns'                   => 20,
                'return_pct'                => 11.76,
                'cod_pct'                   => 0.6,
                'cod_cost_per_order'        => 1.10,
                'avg_speed_days'            => 4.8,
                'contribution_margin'       => 2_100,
                'contribution_margin_pct'   => 21.43,
                'status'                    => 'profitable',
                'detail'                    => self::mockDetail('FI'),
            ],
            [
                'country_code'              => 'PT',
                'country_name'              => 'Portugal',
                'region'                    => 'Europe',
                'orders'                    => 220,
                'revenue'                   => 10_600,
                'avg_shipping_charged'      => 5.90,
                'avg_carrier_cost'          => 7.00,
                'returns'                   => 30,
                'return_pct'                => 13.64,
                'cod_pct'                   => 14.1,
                'cod_cost_per_order'        => 2.30,
                'avg_speed_days'            => 5.2,
                'contribution_margin'       => 1_600,
                'contribution_margin_pct'   => 15.09,
                'status'                    => 'profitable',
                'detail'                    => self::mockDetail('PT'),
            ],
            [
                'country_code'              => 'IE',
                'country_name'              => 'Ireland',
                'region'                    => 'Europe',
                'orders'                    => 150,
                'revenue'                   => 8_700,
                'avg_shipping_charged'      => 8.00,
                'avg_carrier_cost'          => 8.60,
                'returns'                   => 18,
                'return_pct'                => 12.0,
                'cod_pct'                   => 0.0,
                'cod_cost_per_order'        => 0.0,
                'avg_speed_days'            => 4.4,
                'contribution_margin'       => 1_900,
                'contribution_margin_pct'   => 21.84,
                'status'                    => 'profitable',
                'detail'                    => self::mockDetail('IE'),
            ],
            [
                'country_code'              => 'HK',
                'country_name'              => 'Hong Kong',
                'region'                    => 'Asia Pacific',
                'orders'                    => 210,
                'revenue'                   => 13_400,
                'avg_shipping_charged'      => 12.00,
                'avg_carrier_cost'          => 11.40,
                'returns'                   => 9,
                'return_pct'                => 4.29,
                'cod_pct'                   => 0.0,
                'cod_cost_per_order'        => 0.0,
                'avg_speed_days'            => 8.2,
                'contribution_margin'       => 3_200,
                'contribution_margin_pct'   => 23.88,
                'status'                    => 'profitable',
                'detail'                    => self::mockDetail('HK'),
            ],
            [
                'country_code'              => 'MY',
                'country_name'              => 'Malaysia',
                'region'                    => 'Asia Pacific',
                'orders'                    => 160,
                'revenue'                   => 8_900,
                'avg_shipping_charged'      => 11.00,
                'avg_carrier_cost'          => 10.20,
                'returns'                   => 10,
                'return_pct'                => 6.25,
                'cod_pct'                   => 8.1,
                'cod_cost_per_order'        => 2.00,
                'avg_speed_days'            => 9.6,
                'contribution_margin'       => 2_000,
                'contribution_margin_pct'   => 22.47,
                'status'                    => 'profitable',
                'detail'                    => self::mockDetail('MY'),
            ],
            [
                'country_code'              => 'IN',
                'country_name'              => 'India',
                'region'                    => 'Asia Pacific',
                'orders'                    => 340,
                'revenue'                   => 14_200,
                'avg_shipping_charged'      => 5.40,
                'avg_carrier_cost'          => 6.80,
                'returns'                   => 68,
                'return_pct'                => 20.0,
                'cod_pct'                   => 48.2,
                'cod_cost_per_order'        => 2.60,
                'avg_speed_days'            => 8.4,
                'contribution_margin'       => 800,
                'contribution_margin_pct'   => 5.63,
                'status'                    => 'marginal',
                'detail'                    => self::mockDetail('IN'),
            ],
            [
                'country_code'              => 'ZA',
                'country_name'              => 'South Africa',
                'region'                    => 'Africa',
                'orders'                    => 130,
                'revenue'                   => 6_800,
                'avg_shipping_charged'      => 14.00,
                'avg_carrier_cost'          => 16.40,
                'returns'                   => 16,
                'return_pct'                => 12.31,
                'cod_pct'                   => 22.3,
                'cod_cost_per_order'        => 3.10,
                'avg_speed_days'            => 11.2,
                'contribution_margin'       => 400,
                'contribution_margin_pct'   => 5.88,
                'status'                    => 'marginal',
                'detail'                    => self::mockDetail('ZA'),
            ],
            [
                'country_code'              => 'BR',
                'country_name'              => 'Brazil',
                'region'                    => 'Americas',
                'orders'                    => 260,
                'revenue'                   => 12_800,
                'avg_shipping_charged'      => 9.60,
                'avg_carrier_cost'          => 11.80,
                'returns'                   => 39,
                'return_pct'                => 15.0,
                'cod_pct'                   => 32.7,
                'cod_cost_per_order'        => 2.80,
                'avg_speed_days'            => 12.4,
                'contribution_margin'       => 600,
                'contribution_margin_pct'   => 4.69,
                'status'                    => 'marginal',
                'detail'                    => self::mockDetail('BR'),
            ],
            [
                'country_code'              => 'MX',
                'country_name'              => 'Mexico',
                'region'                    => 'Americas',
                'orders'                    => 200,
                'revenue'                   => 9_600,
                'avg_shipping_charged'      => 8.20,
                'avg_carrier_cost'          => 10.40,
                'returns'                   => 30,
                'return_pct'                => 15.0,
                'cod_pct'                   => 28.5,
                'cod_cost_per_order'        => 2.50,
                'avg_speed_days'            => 10.8,
                'contribution_margin'       => -200,
                'contribution_margin_pct'   => -2.08,
                'status'                    => 'loss',
                'detail'                    => self::mockDetail('MX'),
            ],
            [
                'country_code'              => 'AE',
                'country_name'              => 'UAE',
                'region'                    => 'Middle East',
                'orders'                    => 180,
                'revenue'                   => 11_400,
                'avg_shipping_charged'      => 16.00,
                'avg_carrier_cost'          => 14.80,
                'returns'                   => 14,
                'return_pct'                => 7.78,
                'cod_pct'                   => 38.9,
                'cod_cost_per_order'        => 3.80,
                'avg_speed_days'            => 8.6,
                'contribution_margin'       => 2_200,
                'contribution_margin_pct'   => 19.3,
                'status'                    => 'profitable',
                'detail'                    => self::mockDetail('AE'),
            ],
            [
                'country_code'              => 'SA',
                'country_name'              => 'Saudi Arabia',
                'region'                    => 'Middle East',
                'orders'                    => 150,
                'revenue'                   => 9_800,
                'avg_shipping_charged'      => 18.00,
                'avg_carrier_cost'          => 16.40,
                'returns'                   => 12,
                'return_pct'                => 8.0,
                'cod_pct'                   => 44.7,
                'cod_cost_per_order'        => 3.90,
                'avg_speed_days'            => 9.4,
                'contribution_margin'       => 1_700,
                'contribution_margin_pct'   => 17.35,
                'status'                    => 'profitable',
                'detail'                    => self::mockDetail('SA'),
            ],
            [
                'country_code'              => 'CZ',
                'country_name'              => 'Czech Republic',
                'region'                    => 'Europe',
                'orders'                    => 190,
                'revenue'                   => 8_200,
                'avg_shipping_charged'      => 5.20,
                'avg_carrier_cost'          => 6.10,
                'returns'                   => 34,
                'return_pct'                => 17.89,
                'cod_pct'                   => 29.5,
                'cod_cost_per_order'        => 2.40,
                'avg_speed_days'            => 4.1,
                'contribution_margin'       => 1_100,
                'contribution_margin_pct'   => 13.41,
                'status'                    => 'marginal',
                'detail'                    => self::mockDetail('CZ'),
            ],
            [
                'country_code'              => 'HU',
                'country_name'              => 'Hungary',
                'region'                    => 'Europe',
                'orders'                    => 140,
                'revenue'                   => 5_900,
                'avg_shipping_charged'      => 4.90,
                'avg_carrier_cost'          => 5.80,
                'returns'                   => 28,
                'return_pct'                => 20.0,
                'cod_pct'                   => 41.4,
                'cod_cost_per_order'        => 2.50,
                'avg_speed_days'            => 4.8,
                'contribution_margin'       => 400,
                'contribution_margin_pct'   => 6.78,
                'status'                    => 'marginal',
                'detail'                    => self::mockDetail('HU'),
            ],
            [
                'country_code'              => 'SK',
                'country_name'              => 'Slovakia',
                'region'                    => 'Europe',
                'orders'                    => 110,
                'revenue'                   => 4_800,
                'avg_shipping_charged'      => 5.10,
                'avg_carrier_cost'          => 6.20,
                'returns'                   => 22,
                'return_pct'                => 20.0,
                'cod_pct'                   => 38.2,
                'cod_cost_per_order'        => 2.30,
                'avg_speed_days'            => 4.2,
                'contribution_margin'       => 200,
                'contribution_margin_pct'   => 4.17,
                'status'                    => 'marginal',
                'detail'                    => self::mockDetail('SK'),
            ],
            [
                'country_code'              => 'HR',
                'country_name'              => 'Croatia',
                'region'                    => 'Europe',
                'orders'                    => 90,
                'revenue'                   => 3_600,
                'avg_shipping_charged'      => 5.40,
                'avg_carrier_cost'          => 7.10,
                'returns'                   => 27,
                'return_pct'                => 30.0,
                'cod_pct'                   => 55.6,
                'cod_cost_per_order'        => 2.80,
                'avg_speed_days'            => 5.9,
                'contribution_margin'       => -400,
                'contribution_margin_pct'   => -11.11,
                'status'                    => 'loss',
                'detail'                    => self::mockDetail('HR'),
            ],
            [
                'country_code'              => 'TH',
                'country_name'              => 'Thailand',
                'region'                    => 'Asia Pacific',
                'orders'                    => 120,
                'revenue'                   => 6_200,
                'avg_shipping_charged'      => 10.50,
                'avg_carrier_cost'          => 9.80,
                'returns'                   => 8,
                'return_pct'                => 6.67,
                'cod_pct'                   => 22.5,
                'cod_cost_per_order'        => 2.20,
                'avg_speed_days'            => 10.4,
                'contribution_margin'       => 1_300,
                'contribution_margin_pct'   => 20.97,
                'status'                    => 'profitable',
                'detail'                    => self::mockDetail('TH'),
            ],
            [
                'country_code'              => 'PH',
                'country_name'              => 'Philippines',
                'region'                    => 'Asia Pacific',
                'orders'                    => 100,
                'revenue'                   => 4_800,
                'avg_shipping_charged'      => 13.00,
                'avg_carrier_cost'          => 12.60,
                'returns'                   => 8,
                'return_pct'                => 8.0,
                'cod_pct'                   => 34.0,
                'cod_cost_per_order'        => 2.40,
                'avg_speed_days'            => 11.8,
                'contribution_margin'       => 900,
                'contribution_margin_pct'   => 18.75,
                'status'                    => 'profitable',
                'detail'                    => self::mockDetail('PH'),
            ],

            // ── Loss/remote markets ───────────────────────────────────────────
            [
                'country_code'              => 'FJ',
                'country_name'              => 'Fiji',
                'region'                    => 'Pacific',
                'orders'                    => 28,
                'revenue'                   => 1_800,
                'avg_shipping_charged'      => 18.00,
                'avg_carrier_cost'          => 42.00,
                'returns'                   => 3,
                'return_pct'                => 10.71,
                'cod_pct'                   => 0.0,
                'cod_cost_per_order'        => 0.0,
                'avg_speed_days'            => 21.0,
                'contribution_margin'       => -820,
                'contribution_margin_pct'   => -45.56,
                'status'                    => 'loss',
                'detail'                    => self::mockDetail('FJ'),
            ],
            [
                'country_code'              => 'PF',
                'country_name'              => 'French Polynesia',
                'region'                    => 'Pacific',
                'orders'                    => 14,
                'revenue'                   => 980,
                'avg_shipping_charged'      => 24.00,
                'avg_carrier_cost'          => 45.00,
                'returns'                   => 2,
                'return_pct'                => 14.29,
                'cod_pct'                   => 0.0,
                'cod_cost_per_order'        => 0.0,
                'avg_speed_days'            => 28.0,
                'contribution_margin'       => -540,
                'contribution_margin_pct'   => -55.1,
                'status'                    => 'loss',
                'detail'                    => self::mockDetail('PF'),
            ],
            [
                'country_code'              => 'SB',
                'country_name'              => 'Solomon Islands',
                'region'                    => 'Pacific',
                'orders'                    => 8,
                'revenue'                   => 560,
                'avg_shipping_charged'      => 28.00,
                'avg_carrier_cost'          => 48.00,
                'returns'                   => 1,
                'return_pct'                => 12.5,
                'cod_pct'                   => 0.0,
                'cod_cost_per_order'        => 0.0,
                'avg_speed_days'            => 35.0,
                'contribution_margin'       => -310,
                'contribution_margin_pct'   => -55.36,
                'status'                    => 'loss',
                'detail'                    => self::mockDetail('SB'),
            ],
            [
                'country_code'              => 'WS',
                'country_name'              => 'Samoa',
                'region'                    => 'Pacific',
                'orders'                    => 6,
                'revenue'                   => 420,
                'avg_shipping_charged'      => 22.00,
                'avg_carrier_cost'          => 44.00,
                'returns'                   => 0,
                'return_pct'                => 0.0,
                'cod_pct'                   => 0.0,
                'cod_cost_per_order'        => 0.0,
                'avg_speed_days'            => 32.0,
                'contribution_margin'       => -200,
                'contribution_margin_pct'   => -47.62,
                'status'                    => 'loss',
                'detail'                    => self::mockDetail('WS'),
            ],
            [
                'country_code'              => 'EG',
                'country_name'              => 'Egypt',
                'region'                    => 'Africa',
                'orders'                    => 160,
                'revenue'                   => 6_400,
                'avg_shipping_charged'      => 6.00,
                'avg_carrier_cost'          => 9.60,
                'returns'                   => 48,
                'return_pct'                => 30.0,
                'cod_pct'                   => 62.5,
                'cod_cost_per_order'        => 3.20,
                'avg_speed_days'            => 9.8,
                'contribution_margin'       => -1_100,
                'contribution_margin_pct'   => -17.19,
                'status'                    => 'loss',
                'detail'                    => self::mockDetail('EG'),
            ],
            [
                'country_code'              => 'IL',
                'country_name'              => 'Israel',
                'region'                    => 'Middle East',
                'orders'                    => 130,
                'revenue'                   => 7_800,
                'avg_shipping_charged'      => 14.00,
                'avg_carrier_cost'          => 13.20,
                'returns'                   => 13,
                'return_pct'                => 10.0,
                'cod_pct'                   => 0.0,
                'cod_cost_per_order'        => 0.0,
                'avg_speed_days'            => 9.2,
                'contribution_margin'       => 1_600,
                'contribution_margin_pct'   => 20.51,
                'status'                    => 'profitable',
                'detail'                    => self::mockDetail('IL'),
            ],
            [
                'country_code'              => 'UA',
                'country_name'              => 'Ukraine',
                'region'                    => 'Europe',
                'orders'                    => 80,
                'revenue'                   => 3_200,
                'avg_shipping_charged'      => 3.80,
                'avg_carrier_cost'          => 7.20,
                'returns'                   => 24,
                'return_pct'                => 30.0,
                'cod_pct'                   => 78.8,
                'cod_cost_per_order'        => 2.90,
                'avg_speed_days'            => 8.6,
                'contribution_margin'       => -800,
                'contribution_margin_pct'   => -25.0,
                'status'                    => 'loss',
                'detail'                    => self::mockDetail('UA'),
            ],
            [
                'country_code'              => 'NG',
                'country_name'              => 'Nigeria',
                'region'                    => 'Africa',
                'orders'                    => 70,
                'revenue'                   => 3_500,
                'avg_shipping_charged'      => 16.00,
                'avg_carrier_cost'          => 22.00,
                'returns'                   => 14,
                'return_pct'                => 20.0,
                'cod_pct'                   => 57.1,
                'cod_cost_per_order'        => 3.60,
                'avg_speed_days'            => 14.2,
                'contribution_margin'       => -700,
                'contribution_margin_pct'   => -20.0,
                'status'                    => 'loss',
                'detail'                    => self::mockDetail('NG'),
            ],
            [
                'country_code'              => 'KE',
                'country_name'              => 'Kenya',
                'region'                    => 'Africa',
                'orders'                    => 55,
                'revenue'                   => 2_800,
                'avg_shipping_charged'      => 16.00,
                'avg_carrier_cost'          => 19.80,
                'returns'                   => 8,
                'return_pct'                => 14.55,
                'cod_pct'                   => 43.6,
                'cod_cost_per_order'        => 3.40,
                'avg_speed_days'            => 13.6,
                'contribution_margin'       => -300,
                'contribution_margin_pct'   => -10.71,
                'status'                    => 'loss',
                'detail'                    => self::mockDetail('KE'),
            ],
        ];
    }

    /**
     * Per-country detail for the DrawerSidePanel.
     * Returns daily orders (7d), top products, top channels, return reasons, carrier mix.
     *
     * @return array<string, mixed>
     */
    private static function mockDetail(string $countryCode): array
    {
        // Deterministic pseudo-random seeded by country code sum for consistent renders.
        $seed = array_sum(array_map('ord', str_split($countryCode)));

        $dailyOrders = [];
        for ($i = 6; $i >= 0; $i--) {
            $dailyOrders[] = [
                'date'   => now()->subDays($i)->toDateString(),
                'orders' => 10 + (($seed + $i * 7) % 40),
            ];
        }

        return [
            'daily_orders'   => $dailyOrders,
            'top_products'   => [
                ['name' => 'Premium Widget A', 'orders' => 12 + ($seed % 20), 'revenue' => 720 + ($seed * 3)],
                ['name' => 'Classic Widget B', 'orders' => 8 + ($seed % 15),  'revenue' => 480 + ($seed * 2)],
                ['name' => 'Bundle Pack',      'orders' => 5 + ($seed % 10),  'revenue' => 350 + ($seed)],
            ],
            'top_channels'   => [
                ['channel' => 'Facebook Ads',   'orders' => 14 + ($seed % 18), 'pct' => 38],
                ['channel' => 'Google Ads',     'orders' => 10 + ($seed % 12), 'pct' => 27],
                ['channel' => 'Organic Search', 'orders' => 8 + ($seed % 8),   'pct' => 21],
            ],
            'return_reasons' => [
                ['reason' => 'Wrong size / fit',    'pct' => 38],
                ['reason' => 'Changed mind',        'pct' => 28],
                ['reason' => 'Damaged in transit',  'pct' => 18],
                ['reason' => 'Not as described',    'pct' => 12],
                ['reason' => 'Other',               'pct' =>  4],
            ],
            'carrier_mix'    => [
                ['carrier' => 'DHL',    'pct' => 42],
                ['carrier' => 'FedEx',  'pct' => 28],
                ['carrier' => 'UPS',    'pct' => 20],
                ['carrier' => 'Local',  'pct' => 10],
            ],
        ];
    }

    /**
     * Workspace-level summary KPIs for the 4-card strip above the table.
     *
     * @return array<string, mixed>
     */
    private static function mockSummary(): array
    {
        return [
            'avg_shipping_charged'    => 7.84,
            'avg_carrier_cost'        => 8.62,
            'blended_return_rate'     => 10.4,
            'cod_penetration_pct'     => 14.8,
            'countries_profitable'    => 28,
            'countries_marginal'      => 9,
            'countries_loss'          => 13,
            'total_countries'         => 50,
        ];
    }
}
