<?php

declare(strict_types=1);

namespace App\Http\Controllers;

use App\Services\WorkspaceContext;
use App\Models\Workspace;
use Illuminate\Http\Request;
use Inertia\Inertia;
use Inertia\Response;

/**
 * HolidaysController — Campaign calendar planning tool.
 *
 * Returns a Holidays/Index Inertia page with mock holiday/sale-event data
 * covering 12 months across 11 major ecommerce markets. No DB queries —
 * all data is static mock until the holidays service layer is built (L5+).
 *
 * Reads:  WorkspaceContext (for primary country default selection)
 * Writes: nothing
 * Called by: GET /{workspace:slug}/holidays
 *
 * @see docs/pages/holidays.md
 * @see docs/UX.md §5 shared primitives (MetricCardCompact, DrawerSidePanel, DataTable)
 * @see docs/planning/backend.md §HolidaysController
 */
class HolidaysController extends Controller
{
    public function index(Request $request): Response
    {
        $workspaceId = app(WorkspaceContext::class)->id();
        $workspace   = Workspace::withoutGlobalScopes()->findOrFail($workspaceId);

        // Default selected countries: workspace primary country + 2 popular ecommerce markets.
        // Falls back to US if no primary country configured.
        $primaryCountry   = strtoupper($workspace->primary_country_code ?? 'US');
        $defaultSelected  = array_unique(array_filter([$primaryCountry, 'US', 'GB']));

        return Inertia::render('Holidays/Index', [
            'defaultSelectedCountries' => array_values($defaultSelected),
            'events'                   => self::mockEvents(),
            'alertConfig'              => [
                'default_notify_days' => [7, 14, 30],
                'channels'            => ['email', 'slack'],
                'active_channel'      => 'email',
            ],
        ]);
    }

    /**
     * 100+ upcoming holiday / sale events across 11 markets.
     * Dates set relative to 2026 (matches the currentDate in MEMORY.md: 2026-04-30).
     *
     * @return array<int, array<string, mixed>>
     */
    private static function mockEvents(): array
    {
        return [
            // ── US ──────────────────────────────────────────────────────────────
            [
                'id'                       => 'evt_us_memorialday_2026',
                'name'                     => 'Memorial Day',
                'date'                     => '2026-05-25',
                'country_code'             => 'US',
                'country_name'             => 'United States',
                'type'                     => 'statutory_holiday',
                'importance'               => 'medium',
                'recommended_prep_days'    => 14,
                'historical_sales_lift_pct'=> 22,
                'description'              => 'Start-of-summer sale anchor. Apparel, outdoor goods, and home categories see strongest lift. Begin email sequences 2 weeks prior.',
                'is_subscribed'            => true,
                'notify_days_before'       => [7, 14],
                'tags'                     => ['summer', 'sales'],
            ],
            [
                'id'                       => 'evt_us_mothersday_2026',
                'name'                     => "Mother's Day",
                'date'                     => '2026-05-10',
                'country_code'             => 'US',
                'country_name'             => 'United States',
                'type'                     => 'cultural',
                'importance'               => 'high',
                'recommended_prep_days'    => 21,
                'historical_sales_lift_pct'=> 41,
                'description'              => "Second-largest gifting event in the US. Jewelry, flowers, beauty, and experiences dominate. Run gift-guide content 3 weeks before.",
                'is_subscribed'            => true,
                'notify_days_before'       => [7, 14],
                'tags'                     => ['gifting', 'seasonal'],
            ],
            [
                'id'                       => 'evt_us_fathersday_2026',
                'name'                     => "Father's Day",
                'date'                     => '2026-06-21',
                'country_code'             => 'US',
                'country_name'             => 'United States',
                'type'                     => 'cultural',
                'importance'               => 'medium',
                'recommended_prep_days'    => 14,
                'historical_sales_lift_pct'=> 28,
                'description'              => "Gadgets, tools, sportswear, and grooming top the Father's Day charts. Start promotions 2 weeks out.",
                'is_subscribed'            => false,
                'notify_days_before'       => [7],
                'tags'                     => ['gifting'],
            ],
            [
                'id'                       => 'evt_us_independenceday_2026',
                'name'                     => 'Independence Day (4th of July)',
                'date'                     => '2026-07-04',
                'country_code'             => 'US',
                'country_name'             => 'United States',
                'type'                     => 'statutory_holiday',
                'importance'               => 'medium',
                'recommended_prep_days'    => 10,
                'historical_sales_lift_pct'=> 18,
                'description'              => 'Mid-summer clearance and patriotic-themed promotions. Flash sales work well on the day itself.',
                'is_subscribed'            => false,
                'notify_days_before'       => [7],
                'tags'                     => ['summer', 'clearance'],
            ],
            [
                'id'                       => 'evt_us_backtoschool_2026',
                'name'                     => 'Back to School',
                'date'                     => '2026-08-15',
                'country_code'             => 'US',
                'country_name'             => 'United States',
                'type'                     => 'back_to_school',
                'importance'               => 'high',
                'recommended_prep_days'    => 30,
                'historical_sales_lift_pct'=> 55,
                'description'              => 'Runs July through early September. Electronics, clothing, and supplies peak in mid-August. Begin campaigns in July.',
                'is_subscribed'            => true,
                'notify_days_before'       => [14, 30],
                'tags'                     => ['back_to_school', 'seasonal'],
            ],
            [
                'id'                       => 'evt_us_laborday_2026',
                'name'                     => 'Labor Day',
                'date'                     => '2026-09-07',
                'country_code'             => 'US',
                'country_name'             => 'United States',
                'type'                     => 'statutory_holiday',
                'importance'               => 'medium',
                'recommended_prep_days'    => 14,
                'historical_sales_lift_pct'=> 20,
                'description'              => 'End-of-summer clearance. Furniture and mattresses see outsized lift. Overlap with back-to-school tail.',
                'is_subscribed'            => false,
                'notify_days_before'       => [7],
                'tags'                     => ['clearance', 'summer'],
            ],
            [
                'id'                       => 'evt_us_halloween_2026',
                'name'                     => 'Halloween',
                'date'                     => '2026-10-31',
                'country_code'             => 'US',
                'country_name'             => 'United States',
                'type'                     => 'cultural',
                'importance'               => 'medium',
                'recommended_prep_days'    => 21,
                'historical_sales_lift_pct'=> 35,
                'description'              => 'Costumes, candy, home decor, and novelty items. Runs the full month of October. Email and social drive well.',
                'is_subscribed'            => true,
                'notify_days_before'       => [7, 14],
                'tags'                     => ['seasonal', 'cultural'],
            ],
            [
                'id'                       => 'evt_us_thanksgiving_2026',
                'name'                     => 'Thanksgiving',
                'date'                     => '2026-11-26',
                'country_code'             => 'US',
                'country_name'             => 'United States',
                'type'                     => 'statutory_holiday',
                'importance'               => 'high',
                'recommended_prep_days'    => 21,
                'historical_sales_lift_pct'=> 120,
                'description'              => 'Launches the holiday shopping season. Food, home, and gifting categories surge. Tee up Black Friday campaigns this day.',
                'is_subscribed'            => true,
                'notify_days_before'       => [7, 14, 30],
                'tags'                     => ['holiday', 'gifting'],
            ],
            [
                'id'                       => 'evt_us_blackfriday_2026',
                'name'                     => 'Black Friday',
                'date'                     => '2026-11-27',
                'country_code'             => 'US',
                'country_name'             => 'United States',
                'type'                     => 'shopping_event',
                'importance'               => 'high',
                'recommended_prep_days'    => 30,
                'historical_sales_lift_pct'=> 248,
                'description'              => 'The biggest single-day sales event in US ecommerce. Plan email campaigns 4 weeks ahead, ad budget surge starts 2 weeks ahead.',
                'is_subscribed'            => true,
                'notify_days_before'       => [7, 14, 30],
                'tags'                     => ['ecommerce', 'sales', 'must-do'],
            ],
            [
                'id'                       => 'evt_us_cybermonday_2026',
                'name'                     => 'Cyber Monday',
                'date'                     => '2026-11-30',
                'country_code'             => 'US',
                'country_name'             => 'United States',
                'type'                     => 'shopping_event',
                'importance'               => 'high',
                'recommended_prep_days'    => 21,
                'historical_sales_lift_pct'=> 198,
                'description'              => 'Electronics and software lead. Run email reminders the Sunday before. Extend deals through "Cyber Week" for more volume.',
                'is_subscribed'            => true,
                'notify_days_before'       => [7, 14],
                'tags'                     => ['ecommerce', 'tech', 'must-do'],
            ],
            [
                'id'                       => 'evt_us_christmas_2026',
                'name'                     => 'Christmas',
                'date'                     => '2026-12-25',
                'country_code'             => 'US',
                'country_name'             => 'United States',
                'type'                     => 'statutory_holiday',
                'importance'               => 'high',
                'recommended_prep_days'    => 45,
                'historical_sales_lift_pct'=> 310,
                'description'              => 'Peak gifting season. Holiday gift guides from early November. Shipping cutoff messaging crucial in mid-December.',
                'is_subscribed'            => true,
                'notify_days_before'       => [14, 30],
                'tags'                     => ['holiday', 'gifting', 'must-do'],
            ],
            [
                'id'                       => 'evt_us_newyears_2027',
                'name'                     => "New Year's Day",
                'date'                     => '2027-01-01',
                'country_code'             => 'US',
                'country_name'             => 'United States',
                'type'                     => 'statutory_holiday',
                'importance'               => 'low',
                'recommended_prep_days'    => 7,
                'historical_sales_lift_pct'=> 12,
                'description'              => 'Post-holiday clearance and resolution-themed products (fitness, planners, self-improvement) peak January 1-7.',
                'is_subscribed'            => false,
                'notify_days_before'       => [7],
                'tags'                     => ['clearance'],
            ],
            [
                'id'                       => 'evt_us_valentinesday_2027',
                'name'                     => "Valentine's Day",
                'date'                     => '2027-02-14',
                'country_code'             => 'US',
                'country_name'             => 'United States',
                'type'                     => 'cultural',
                'importance'               => 'high',
                'recommended_prep_days'    => 21,
                'historical_sales_lift_pct'=> 62,
                'description'              => "Third-largest gifting event. Jewelry, flowers, candy, and experiences. Run gift-guide campaigns starting February 1.",
                'is_subscribed'            => true,
                'notify_days_before'       => [7, 14],
                'tags'                     => ['gifting', 'seasonal'],
            ],
            [
                'id'                       => 'evt_us_presidentsday_2027',
                'name'                     => "Presidents' Day",
                'date'                     => '2027-02-15',
                'country_code'             => 'US',
                'country_name'             => 'United States',
                'type'                     => 'statutory_holiday',
                'importance'               => 'low',
                'recommended_prep_days'    => 7,
                'historical_sales_lift_pct'=> 14,
                'description'              => 'Mattress, furniture, and auto dealership traditional. Modest ecommerce lift for home goods.',
                'is_subscribed'            => false,
                'notify_days_before'       => [7],
                'tags'                     => ['sales'],
            ],

            // ── UK ──────────────────────────────────────────────────────────────
            [
                'id'                       => 'evt_uk_bankholiday_may_2026',
                'name'                     => 'Early May Bank Holiday',
                'date'                     => '2026-05-04',
                'country_code'             => 'GB',
                'country_name'             => 'United Kingdom',
                'type'                     => 'statutory_holiday',
                'importance'               => 'low',
                'recommended_prep_days'    => 7,
                'historical_sales_lift_pct'=> 8,
                'description'              => 'Long-weekend uplift for home, garden, and DIY products. Small promotional window.',
                'is_subscribed'            => false,
                'notify_days_before'       => [7],
                'tags'                     => ['bank_holiday'],
            ],
            [
                'id'                       => 'evt_uk_bankholiday_spring_2026',
                'name'                     => 'Spring Bank Holiday',
                'date'                     => '2026-05-25',
                'country_code'             => 'GB',
                'country_name'             => 'United Kingdom',
                'type'                     => 'statutory_holiday',
                'importance'               => 'low',
                'recommended_prep_days'    => 7,
                'historical_sales_lift_pct'=> 10,
                'description'              => 'Pre-summer long weekend. Garden, fashion, and outdoor categories see modest lift.',
                'is_subscribed'            => false,
                'notify_days_before'       => [7],
                'tags'                     => ['bank_holiday'],
            ],
            [
                'id'                       => 'evt_uk_bankholiday_aug_2026',
                'name'                     => 'August Bank Holiday',
                'date'                     => '2026-08-31',
                'country_code'             => 'GB',
                'country_name'             => 'United Kingdom',
                'type'                     => 'statutory_holiday',
                'importance'               => 'low',
                'recommended_prep_days'    => 7,
                'historical_sales_lift_pct'=> 9,
                'description'              => 'End-of-summer long weekend. Clearance sales and back-to-school overlap.',
                'is_subscribed'            => false,
                'notify_days_before'       => [7],
                'tags'                     => ['bank_holiday', 'clearance'],
            ],
            [
                'id'                       => 'evt_uk_blackfriday_2026',
                'name'                     => 'Black Friday',
                'date'                     => '2026-11-27',
                'country_code'             => 'GB',
                'country_name'             => 'United Kingdom',
                'type'                     => 'shopping_event',
                'importance'               => 'high',
                'recommended_prep_days'    => 30,
                'historical_sales_lift_pct'=> 185,
                'description'              => 'UK Black Friday is now as large as the US event. Fashion, tech, and home lead. Prepare email sequences 4 weeks out.',
                'is_subscribed'            => true,
                'notify_days_before'       => [7, 14, 30],
                'tags'                     => ['ecommerce', 'sales', 'must-do'],
            ],
            [
                'id'                       => 'evt_uk_cybermonday_2026',
                'name'                     => 'Cyber Monday',
                'date'                     => '2026-11-30',
                'country_code'             => 'GB',
                'country_name'             => 'United Kingdom',
                'type'                     => 'shopping_event',
                'importance'               => 'high',
                'recommended_prep_days'    => 14,
                'historical_sales_lift_pct'=> 142,
                'description'              => 'Strong in UK for electronics and software. Extend Black Friday deals through Cyber Week.',
                'is_subscribed'            => true,
                'notify_days_before'       => [7, 14],
                'tags'                     => ['ecommerce', 'tech'],
            ],
            [
                'id'                       => 'evt_uk_christmas_2026',
                'name'                     => 'Christmas',
                'date'                     => '2026-12-25',
                'country_code'             => 'GB',
                'country_name'             => 'United Kingdom',
                'type'                     => 'statutory_holiday',
                'importance'               => 'high',
                'recommended_prep_days'    => 45,
                'historical_sales_lift_pct'=> 290,
                'description'              => 'Peak gifting season. Gift guides from November. Shipping cutoffs critical. "Christmas delivery guaranteed" messaging.',
                'is_subscribed'            => true,
                'notify_days_before'       => [14, 30],
                'tags'                     => ['holiday', 'gifting', 'must-do'],
            ],
            [
                'id'                       => 'evt_uk_boxingday_2026',
                'name'                     => 'Boxing Day',
                'date'                     => '2026-12-26',
                'country_code'             => 'GB',
                'country_name'             => 'United Kingdom',
                'type'                     => 'shopping_event',
                'importance'               => 'high',
                'recommended_prep_days'    => 14,
                'historical_sales_lift_pct'=> 165,
                'description'              => "The UK's biggest post-Christmas sale. Massive discounting. Prepare Boxing Day deals announcement for Christmas morning email.",
                'is_subscribed'            => true,
                'notify_days_before'       => [7, 14],
                'tags'                     => ['ecommerce', 'sales', 'clearance'],
            ],
            [
                'id'                       => 'evt_uk_easter_2027',
                'name'                     => 'Easter Bank Holiday',
                'date'                     => '2027-04-02',
                'country_code'             => 'GB',
                'country_name'             => 'United Kingdom',
                'type'                     => 'statutory_holiday',
                'importance'               => 'medium',
                'recommended_prep_days'    => 14,
                'historical_sales_lift_pct'=> 38,
                'description'              => 'Long Easter weekend. Chocolate, home, garden, and fashion. Spring collection launch opportunity.',
                'is_subscribed'            => false,
                'notify_days_before'       => [7, 14],
                'tags'                     => ['seasonal', 'spring'],
            ],

            // ── DE ──────────────────────────────────────────────────────────────
            [
                'id'                       => 'evt_de_schulanfang_2026',
                'name'                     => 'Schulanfang (Back to School)',
                'date'                     => '2026-09-07',
                'country_code'             => 'DE',
                'country_name'             => 'Germany',
                'type'                     => 'back_to_school',
                'importance'               => 'medium',
                'recommended_prep_days'    => 21,
                'historical_sales_lift_pct'=> 30,
                'description'              => 'Varies by federal state (Aug-Sep). Stationery, backpacks, and electronics lead. Target by state for precise timing.',
                'is_subscribed'            => false,
                'notify_days_before'       => [14],
                'tags'                     => ['back_to_school', 'seasonal'],
            ],
            [
                'id'                       => 'evt_de_blackfriday_2026',
                'name'                     => 'Black Friday',
                'date'                     => '2026-11-27',
                'country_code'             => 'DE',
                'country_name'             => 'Germany',
                'type'                     => 'shopping_event',
                'importance'               => 'high',
                'recommended_prep_days'    => 21,
                'historical_sales_lift_pct'=> 160,
                'description'              => 'Black Friday is now mainstream in Germany. Electronics, fashion, and home goods lead. Localize copy in German.',
                'is_subscribed'            => true,
                'notify_days_before'       => [7, 14],
                'tags'                     => ['ecommerce', 'sales'],
            ],
            [
                'id'                       => 'evt_de_nikolaus_2026',
                'name'                     => 'Nikolaustag (St. Nicholas Day)',
                'date'                     => '2026-12-06',
                'country_code'             => 'DE',
                'country_name'             => 'Germany',
                'type'                     => 'cultural',
                'importance'               => 'medium',
                'recommended_prep_days'    => 14,
                'historical_sales_lift_pct'=> 22,
                'description'              => 'Traditional gift-giving day for children. Small gifts and sweets. Treat as a mini Christmas-lite event.',
                'is_subscribed'            => false,
                'notify_days_before'       => [7],
                'tags'                     => ['gifting', 'cultural'],
            ],
            [
                'id'                       => 'evt_de_weihnachten_2026',
                'name'                     => 'Weihnachten (Christmas)',
                'date'                     => '2026-12-25',
                'country_code'             => 'DE',
                'country_name'             => 'Germany',
                'type'                     => 'statutory_holiday',
                'importance'               => 'high',
                'recommended_prep_days'    => 45,
                'historical_sales_lift_pct'=> 260,
                'description'              => 'Germany\'s biggest retail season. Gift guides, Advent calendar promotions, and last-minute shipping CTAs work well.',
                'is_subscribed'            => true,
                'notify_days_before'       => [14, 30],
                'tags'                     => ['holiday', 'gifting', 'must-do'],
            ],
            [
                'id'                       => 'evt_de_karneval_2027',
                'name'                     => 'Karneval / Fasching',
                'date'                     => '2027-02-11',
                'country_code'             => 'DE',
                'country_name'             => 'Germany',
                'type'                     => 'cultural',
                'importance'               => 'medium',
                'recommended_prep_days'    => 21,
                'historical_sales_lift_pct'=> 28,
                'description'              => 'Carnival season (Rhineland especially). Costumes, party goods, and novelty items peak weeks before Shrove Tuesday.',
                'is_subscribed'            => false,
                'notify_days_before'       => [14],
                'tags'                     => ['cultural', 'seasonal'],
            ],

            // ── FR ──────────────────────────────────────────────────────────────
            [
                'id'                       => 'evt_fr_soldes_ete_2026',
                'name'                     => 'Soldes d\'ete (Summer Sales)',
                'date'                     => '2026-06-25',
                'country_code'             => 'FR',
                'country_name'             => 'France',
                'type'                     => 'shopping_event',
                'importance'               => 'high',
                'recommended_prep_days'    => 21,
                'historical_sales_lift_pct'=> 145,
                'description'              => 'Legally regulated French summer sales (late June/July). Fashion brands must comply with soldes rules. 4-week window.',
                'is_subscribed'            => true,
                'notify_days_before'       => [14, 30],
                'tags'                     => ['regulated', 'fashion', 'sales'],
            ],
            [
                'id'                       => 'evt_fr_bastilleday_2026',
                'name'                     => 'Fete Nationale (Bastille Day)',
                'date'                     => '2026-07-14',
                'country_code'             => 'FR',
                'country_name'             => 'France',
                'type'                     => 'statutory_holiday',
                'importance'               => 'low',
                'recommended_prep_days'    => 7,
                'historical_sales_lift_pct'=> null,
                'description'              => 'National holiday. Consumer spending tends to be low — most are offline. Avoid major campaign launches on this day.',
                'is_subscribed'            => false,
                'notify_days_before'       => [7],
                'tags'                     => ['statutory'],
            ],
            [
                'id'                       => 'evt_fr_blackfriday_2026',
                'name'                     => 'Black Friday',
                'date'                     => '2026-11-27',
                'country_code'             => 'FR',
                'country_name'             => 'France',
                'type'                     => 'shopping_event',
                'importance'               => 'high',
                'recommended_prep_days'    => 21,
                'historical_sales_lift_pct'=> 155,
                'description'              => 'Strong ecommerce event in France despite some consumer pushback. Electronics and home goods lead. Localize in French.',
                'is_subscribed'            => true,
                'notify_days_before'       => [7, 14],
                'tags'                     => ['ecommerce', 'sales'],
            ],
            [
                'id'                       => 'evt_fr_noel_2026',
                'name'                     => 'Noel (Christmas)',
                'date'                     => '2026-12-25',
                'country_code'             => 'FR',
                'country_name'             => 'France',
                'type'                     => 'statutory_holiday',
                'importance'               => 'high',
                'recommended_prep_days'    => 45,
                'historical_sales_lift_pct'=> 245,
                'description'              => 'Peak gifting season. Luxury goods, fashion, toys. French shoppers often finalize Christmas shopping very close to the date.',
                'is_subscribed'            => true,
                'notify_days_before'       => [14, 30],
                'tags'                     => ['holiday', 'gifting'],
            ],
            [
                'id'                       => 'evt_fr_soldes_hiver_2027',
                'name'                     => 'Soldes d\'hiver (Winter Sales)',
                'date'                     => '2027-01-08',
                'country_code'             => 'FR',
                'country_name'             => 'France',
                'type'                     => 'shopping_event',
                'importance'               => 'high',
                'recommended_prep_days'    => 21,
                'historical_sales_lift_pct'=> 130,
                'description'              => 'Legally regulated French winter sales (early January). 4-week mandatory window. Deep discounts on fashion and home.',
                'is_subscribed'            => false,
                'notify_days_before'       => [14],
                'tags'                     => ['regulated', 'fashion', 'sales'],
            ],

            // ── IT ──────────────────────────────────────────────────────────────
            [
                'id'                       => 'evt_it_saldi_estivi_2026',
                'name'                     => 'Saldi Estivi (Summer Sales)',
                'date'                     => '2026-07-04',
                'country_code'             => 'IT',
                'country_name'             => 'Italy',
                'type'                     => 'shopping_event',
                'importance'               => 'high',
                'recommended_prep_days'    => 21,
                'historical_sales_lift_pct'=> 135,
                'description'              => 'Regulated Italian summer sales (starts first Saturday of July). Fashion-forward — clothing and accessories dominate.',
                'is_subscribed'            => false,
                'notify_days_before'       => [14],
                'tags'                     => ['regulated', 'fashion', 'sales'],
            ],
            [
                'id'                       => 'evt_it_blackfriday_2026',
                'name'                     => 'Black Friday',
                'date'                     => '2026-11-27',
                'country_code'             => 'IT',
                'country_name'             => 'Italy',
                'type'                     => 'shopping_event',
                'importance'               => 'high',
                'recommended_prep_days'    => 21,
                'historical_sales_lift_pct'=> 145,
                'description'              => 'Rapidly growing in Italy. Electronics, fashion, and home goods. Italian shoppers respond well to percentage-off framing.',
                'is_subscribed'            => false,
                'notify_days_before'       => [7, 14],
                'tags'                     => ['ecommerce', 'sales'],
            ],
            [
                'id'                       => 'evt_it_natale_2026',
                'name'                     => 'Natale (Christmas)',
                'date'                     => '2026-12-25',
                'country_code'             => 'IT',
                'country_name'             => 'Italy',
                'type'                     => 'statutory_holiday',
                'importance'               => 'high',
                'recommended_prep_days'    => 45,
                'historical_sales_lift_pct'=> 230,
                'description'              => 'Peak gifting season. Panettone, fashion, jewelry, and children\'s toys. Gift packaging and wrapping service offers convert well.',
                'is_subscribed'            => false,
                'notify_days_before'       => [14],
                'tags'                     => ['holiday', 'gifting'],
            ],
            [
                'id'                       => 'evt_it_saldi_invernali_2027',
                'name'                     => 'Saldi Invernali (Winter Sales)',
                'date'                     => '2027-01-05',
                'country_code'             => 'IT',
                'country_name'             => 'Italy',
                'type'                     => 'shopping_event',
                'importance'               => 'high',
                'recommended_prep_days'    => 14,
                'historical_sales_lift_pct'=> 120,
                'description'              => 'Regulated Italian winter sales (starts first working day after Epiphany). Deep fashion discounts.',
                'is_subscribed'            => false,
                'notify_days_before'       => [7, 14],
                'tags'                     => ['regulated', 'fashion', 'clearance'],
            ],

            // ── ES ──────────────────────────────────────────────────────────────
            [
                'id'                       => 'evt_es_sanisidro_2026',
                'name'                     => 'Rebajas de Verano (Summer Sales)',
                'date'                     => '2026-07-01',
                'country_code'             => 'ES',
                'country_name'             => 'Spain',
                'type'                     => 'shopping_event',
                'importance'               => 'high',
                'recommended_prep_days'    => 21,
                'historical_sales_lift_pct'=> 140,
                'description'              => 'Traditional Spanish summer sales season (July-August). Fashion and home goods dominate. Strong in-store and online overlap.',
                'is_subscribed'            => false,
                'notify_days_before'       => [14],
                'tags'                     => ['fashion', 'sales', 'seasonal'],
            ],
            [
                'id'                       => 'evt_es_blackfriday_2026',
                'name'                     => 'Black Friday',
                'date'                     => '2026-11-27',
                'country_code'             => 'ES',
                'country_name'             => 'Spain',
                'type'                     => 'shopping_event',
                'importance'               => 'high',
                'recommended_prep_days'    => 21,
                'historical_sales_lift_pct'=> 170,
                'description'              => 'Spain has strongly adopted Black Friday. Electronics and fashion lead. Spanish shoppers often extend spend into Cyber Week.',
                'is_subscribed'            => false,
                'notify_days_before'       => [7, 14],
                'tags'                     => ['ecommerce', 'sales'],
            ],
            [
                'id'                       => 'evt_es_navidad_2026',
                'name'                     => 'Navidad (Christmas)',
                'date'                     => '2026-12-25',
                'country_code'             => 'ES',
                'country_name'             => 'Spain',
                'type'                     => 'statutory_holiday',
                'importance'               => 'high',
                'recommended_prep_days'    => 45,
                'historical_sales_lift_pct'=> 220,
                'description'              => 'The holiday season in Spain extends to Three Kings Day (Jan 6). Plan two peaks: Christmas and Reyes.',
                'is_subscribed'            => false,
                'notify_days_before'       => [14],
                'tags'                     => ['holiday', 'gifting'],
            ],
            [
                'id'                       => 'evt_es_reyesmagos_2027',
                'name'                     => 'Dia de Reyes (Three Kings Day)',
                'date'                     => '2027-01-06',
                'country_code'             => 'ES',
                'country_name'             => 'Spain',
                'type'                     => 'cultural',
                'importance'               => 'high',
                'recommended_prep_days'    => 21,
                'historical_sales_lift_pct'=> 180,
                'description'              => 'The main gift-giving day in Spain (children receive gifts from the Three Kings, not Santa). Bigger than Christmas day for toys and gifting.',
                'is_subscribed'            => false,
                'notify_days_before'       => [14],
                'tags'                     => ['gifting', 'cultural'],
            ],

            // ── AU ──────────────────────────────────────────────────────────────
            [
                'id'                       => 'evt_au_australiaday_2027',
                'name'                     => 'Australia Day',
                'date'                     => '2027-01-26',
                'country_code'             => 'AU',
                'country_name'             => 'Australia',
                'type'                     => 'statutory_holiday',
                'importance'               => 'medium',
                'recommended_prep_days'    => 14,
                'historical_sales_lift_pct'=> 25,
                'description'              => 'Australia\'s national day. BBQ, outdoor, and home goods peak. Long weekend uplift for ecommerce.',
                'is_subscribed'            => false,
                'notify_days_before'       => [7],
                'tags'                     => ['statutory', 'summer'],
            ],
            [
                'id'                       => 'evt_au_click_frenzy_2026',
                'name'                     => 'Click Frenzy (AU)',
                'date'                     => '2026-11-10',
                'country_code'             => 'AU',
                'country_name'             => 'Australia',
                'type'                     => 'shopping_event',
                'importance'               => 'medium',
                'recommended_prep_days'    => 14,
                'historical_sales_lift_pct'=> 85,
                'description'              => 'Australia\'s online-only shopping event (pre-Black Friday). Electronics, fashion, and travel deals. 24-hour window.',
                'is_subscribed'            => false,
                'notify_days_before'       => [7, 14],
                'tags'                     => ['ecommerce', 'sales'],
            ],
            [
                'id'                       => 'evt_au_blackfriday_2026',
                'name'                     => 'Black Friday',
                'date'                     => '2026-11-27',
                'country_code'             => 'AU',
                'country_name'             => 'Australia',
                'type'                     => 'shopping_event',
                'importance'               => 'high',
                'recommended_prep_days'    => 21,
                'historical_sales_lift_pct'=> 155,
                'description'              => 'Growing fast in Australia. Electronics, fashion, and home goods lead. Note: it falls in late spring/early summer in AU.',
                'is_subscribed'            => false,
                'notify_days_before'       => [7, 14],
                'tags'                     => ['ecommerce', 'sales'],
            ],
            [
                'id'                       => 'evt_au_christmas_2026',
                'name'                     => 'Christmas',
                'date'                     => '2026-12-25',
                'country_code'             => 'AU',
                'country_name'             => 'Australia',
                'type'                     => 'statutory_holiday',
                'importance'               => 'high',
                'recommended_prep_days'    => 45,
                'historical_sales_lift_pct'=> 240,
                'description'              => 'Peak gifting season — in summer for Australians. Beach, outdoor, and lifestyle gifts perform well alongside traditional categories.',
                'is_subscribed'            => false,
                'notify_days_before'       => [14, 30],
                'tags'                     => ['holiday', 'gifting'],
            ],
            [
                'id'                       => 'evt_au_boxingday_2026',
                'name'                     => 'Boxing Day',
                'date'                     => '2026-12-26',
                'country_code'             => 'AU',
                'country_name'             => 'Australia',
                'type'                     => 'shopping_event',
                'importance'               => 'high',
                'recommended_prep_days'    => 14,
                'historical_sales_lift_pct'=> 200,
                'description'              => 'Australia\'s single biggest retail day of the year. Deep discounts across all categories. Prepare Boxing Day deals for Christmas Day email.',
                'is_subscribed'            => true,
                'notify_days_before'       => [7, 14],
                'tags'                     => ['ecommerce', 'sales', 'must-do'],
            ],

            // ── CA ──────────────────────────────────────────────────────────────
            [
                'id'                       => 'evt_ca_canadaday_2026',
                'name'                     => 'Canada Day',
                'date'                     => '2026-07-01',
                'country_code'             => 'CA',
                'country_name'             => 'Canada',
                'type'                     => 'statutory_holiday',
                'importance'               => 'medium',
                'recommended_prep_days'    => 10,
                'historical_sales_lift_pct'=> 18,
                'description'              => 'Canada\'s national day. Outdoor, sporting, and patriotic goods. Bilingual (EN/FR) copy important for Quebec reach.',
                'is_subscribed'            => false,
                'notify_days_before'       => [7],
                'tags'                     => ['statutory', 'summer'],
            ],
            [
                'id'                       => 'evt_ca_blackfriday_2026',
                'name'                     => 'Black Friday',
                'date'                     => '2026-11-27',
                'country_code'             => 'CA',
                'country_name'             => 'Canada',
                'type'                     => 'shopping_event',
                'importance'               => 'high',
                'recommended_prep_days'    => 21,
                'historical_sales_lift_pct'=> 175,
                'description'              => 'Major shopping event in Canada. Electronics, fashion, and home goods. Note CAD exchange rate sensitivity for cross-border shoppers.',
                'is_subscribed'            => false,
                'notify_days_before'       => [7, 14],
                'tags'                     => ['ecommerce', 'sales'],
            ],
            [
                'id'                       => 'evt_ca_cybermonday_2026',
                'name'                     => 'Cyber Monday',
                'date'                     => '2026-11-30',
                'country_code'             => 'CA',
                'country_name'             => 'Canada',
                'type'                     => 'shopping_event',
                'importance'               => 'medium',
                'recommended_prep_days'    => 14,
                'historical_sales_lift_pct'=> 135,
                'description'              => 'Strong in Canada, especially for electronics and subscriptions. Extend Black Friday campaigns through Cyber Week.',
                'is_subscribed'            => false,
                'notify_days_before'       => [7],
                'tags'                     => ['ecommerce', 'tech'],
            ],
            [
                'id'                       => 'evt_ca_christmas_2026',
                'name'                     => 'Christmas',
                'date'                     => '2026-12-25',
                'country_code'             => 'CA',
                'country_name'             => 'Canada',
                'type'                     => 'statutory_holiday',
                'importance'               => 'high',
                'recommended_prep_days'    => 45,
                'historical_sales_lift_pct'=> 270,
                'description'              => 'Peak gifting season. Bilingual market — ensure French translations for Quebec campaigns. Shipping cutoff messaging critical.',
                'is_subscribed'            => false,
                'notify_days_before'       => [14, 30],
                'tags'                     => ['holiday', 'gifting'],
            ],
            [
                'id'                       => 'evt_ca_boxingday_2026',
                'name'                     => 'Boxing Day',
                'date'                     => '2026-12-26',
                'country_code'             => 'CA',
                'country_name'             => 'Canada',
                'type'                     => 'shopping_event',
                'importance'               => 'high',
                'recommended_prep_days'    => 14,
                'historical_sales_lift_pct'=> 165,
                'description'              => 'Major post-Christmas sales event in Canada. Electronics and home goods lead. Coordinate with Boxing Day UK for shared creative assets.',
                'is_subscribed'            => false,
                'notify_days_before'       => [7, 14],
                'tags'                     => ['ecommerce', 'sales'],
            ],

            // ── JP ──────────────────────────────────────────────────────────────
            [
                'id'                       => 'evt_jp_goldenweek_2026',
                'name'                     => 'Golden Week',
                'date'                     => '2026-05-03',
                'country_code'             => 'JP',
                'country_name'             => 'Japan',
                'type'                     => 'statutory_holiday',
                'importance'               => 'high',
                'recommended_prep_days'    => 21,
                'historical_sales_lift_pct'=> 68,
                'description'              => 'Japan\'s biggest holiday cluster (Apr 29 - May 5). Travel and leisure dominate, but fashion, electronics, and gifting also lift. Prepare early.',
                'is_subscribed'            => false,
                'notify_days_before'       => [14],
                'tags'                     => ['statutory', 'seasonal'],
            ],
            [
                'id'                       => 'evt_jp_singlesdayadjacent_2026',
                'name'                     => '11.11 / Singles Day (adjacent)',
                'date'                     => '2026-11-11',
                'country_code'             => 'JP',
                'country_name'             => 'Japan',
                'type'                     => 'shopping_event',
                'importance'               => 'low',
                'recommended_prep_days'    => 14,
                'historical_sales_lift_pct'=> 30,
                'description'              => 'Japan sees some Singles Day spillover from Chinese-adjacent promotions. Smaller than China but growing, especially for electronics.',
                'is_subscribed'            => false,
                'notify_days_before'       => [7],
                'tags'                     => ['ecommerce'],
            ],
            [
                'id'                       => 'evt_jp_blackfriday_2026',
                'name'                     => 'Black Friday',
                'date'                     => '2026-11-27',
                'country_code'             => 'JP',
                'country_name'             => 'Japan',
                'type'                     => 'shopping_event',
                'importance'               => 'medium',
                'recommended_prep_days'    => 14,
                'historical_sales_lift_pct'=> 75,
                'description'              => 'Growing in Japan, especially for electronics and imported brands. Amazon Japan is a major driver. Localize in Japanese.',
                'is_subscribed'            => false,
                'notify_days_before'       => [7],
                'tags'                     => ['ecommerce', 'sales'],
            ],
            [
                'id'                       => 'evt_jp_christmas_2026',
                'name'                     => 'Christmas (Kurisumasu)',
                'date'                     => '2026-12-25',
                'country_code'             => 'JP',
                'country_name'             => 'Japan',
                'type'                     => 'cultural',
                'importance'               => 'medium',
                'recommended_prep_days'    => 14,
                'historical_sales_lift_pct'=> 50,
                'description'              => 'Not a statutory holiday, but culturally celebrated as a couples\' occasion. Sweets, luxury gifts, and date-night experiences.',
                'is_subscribed'            => false,
                'notify_days_before'       => [7, 14],
                'tags'                     => ['cultural', 'gifting'],
            ],

            // ── BR ──────────────────────────────────────────────────────────────
            [
                'id'                       => 'evt_br_carnaval_2027',
                'name'                     => 'Carnaval',
                'date'                     => '2027-02-13',
                'country_code'             => 'BR',
                'country_name'             => 'Brazil',
                'type'                     => 'cultural',
                'importance'               => 'medium',
                'recommended_prep_days'    => 14,
                'historical_sales_lift_pct'=> 35,
                'description'              => 'Costumes, party goods, and festive categories surge weeks before. Logistics disruptions around the carnival week.',
                'is_subscribed'            => false,
                'notify_days_before'       => [14],
                'tags'                     => ['cultural', 'seasonal'],
            ],
            [
                'id'                       => 'evt_br_diadas_maes_2026',
                'name'                     => "Dia das Maes (Mother's Day)",
                'date'                     => '2026-05-10',
                'country_code'             => 'BR',
                'country_name'             => 'Brazil',
                'type'                     => 'cultural',
                'importance'               => 'high',
                'recommended_prep_days'    => 21,
                'historical_sales_lift_pct'=> 90,
                'description'              => 'The biggest retail event in Brazil (second Sunday of May). Exceeds Black Friday in some categories. All consumer goods categories lift.',
                'is_subscribed'            => false,
                'notify_days_before'       => [7, 14],
                'tags'                     => ['gifting', 'must-do'],
            ],
            [
                'id'                       => 'evt_br_blackfriday_2026',
                'name'                     => 'Black Friday',
                'date'                     => '2026-11-27',
                'country_code'             => 'BR',
                'country_name'             => 'Brazil',
                'type'                     => 'shopping_event',
                'importance'               => 'high',
                'recommended_prep_days'    => 21,
                'historical_sales_lift_pct'=> 280,
                'description'              => 'Brazil\'s biggest ecommerce event. Often extends into "Black November." Electronics, fashion, and home goods. Localize in Brazilian Portuguese.',
                'is_subscribed'            => false,
                'notify_days_before'       => [7, 14],
                'tags'                     => ['ecommerce', 'sales', 'must-do'],
            ],
            [
                'id'                       => 'evt_br_natal_2026',
                'name'                     => 'Natal (Christmas)',
                'date'                     => '2026-12-25',
                'country_code'             => 'BR',
                'country_name'             => 'Brazil',
                'type'                     => 'statutory_holiday',
                'importance'               => 'high',
                'recommended_prep_days'    => 30,
                'historical_sales_lift_pct'=> 215,
                'description'              => 'Major gifting season. Toys, electronics, fashion. Brazilians shop heavily in December — "Natal" campaigns run all month.',
                'is_subscribed'            => false,
                'notify_days_before'       => [14],
                'tags'                     => ['holiday', 'gifting'],
            ],

            // ── IN ──────────────────────────────────────────────────────────────
            [
                'id'                       => 'evt_in_holi_2027',
                'name'                     => 'Holi',
                'date'                     => '2027-03-02',
                'country_code'             => 'IN',
                'country_name'             => 'India',
                'type'                     => 'cultural',
                'importance'               => 'medium',
                'recommended_prep_days'    => 14,
                'historical_sales_lift_pct'=> 42,
                'description'              => 'Festival of colors. Fashion (especially colorful clothing), home goods, and sweets. Strong on social media.',
                'is_subscribed'            => false,
                'notify_days_before'       => [7, 14],
                'tags'                     => ['cultural', 'seasonal'],
            ],
            [
                'id'                       => 'evt_in_independenceday_2026',
                'name'                     => 'Independence Day Sale',
                'date'                     => '2026-08-15',
                'country_code'             => 'IN',
                'country_name'             => 'India',
                'type'                     => 'shopping_event',
                'importance'               => 'medium',
                'recommended_prep_days'    => 14,
                'historical_sales_lift_pct'=> 38,
                'description'              => 'Flipkart and Amazon India run major Independence Day sales. A good peg for brands targeting the Indian market.',
                'is_subscribed'            => false,
                'notify_days_before'       => [7],
                'tags'                     => ['sales', 'statutory'],
            ],
            [
                'id'                       => 'evt_in_diwali_2026',
                'name'                     => 'Diwali (Festival of Lights)',
                'date'                     => '2026-10-20',
                'country_code'             => 'IN',
                'country_name'             => 'India',
                'type'                     => 'cultural',
                'importance'               => 'high',
                'recommended_prep_days'    => 30,
                'historical_sales_lift_pct'=> 320,
                'description'              => 'India\'s biggest shopping event by far. Electronics, jewelry, home, and gifting explode. Diwali season runs 2 weeks. The Indian equivalent of Christmas + Black Friday combined.',
                'is_subscribed'            => false,
                'notify_days_before'       => [14, 30],
                'tags'                     => ['cultural', 'gifting', 'must-do'],
            ],
            [
                'id'                       => 'evt_in_blackfriday_2026',
                'name'                     => 'Black Friday',
                'date'                     => '2026-11-27',
                'country_code'             => 'IN',
                'country_name'             => 'India',
                'type'                     => 'shopping_event',
                'importance'               => 'low',
                'recommended_prep_days'    => 7,
                'historical_sales_lift_pct'=> 30,
                'description'              => 'Small but growing in urban India, primarily for electronics and international brands. Less significant than Diwali season.',
                'is_subscribed'            => false,
                'notify_days_before'       => [7],
                'tags'                     => ['ecommerce'],
            ],
        ];
    }
}
