<?php

declare(strict_types=1);

namespace App\Http\Controllers;

use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Inertia\Inertia;
use Inertia\Response;

/**
 * Products page — workspace-scoped product table + inline COGS edit.
 *
 * Thin controller: all aggregation will be delegated to ProductsDataService once
 * the service layer is built. Until then, returns mock prop data so the
 * frontend is fully renderable without any DB dependency.
 *
 * Prop shape matches Products/Index.tsx exactly:
 *   products, metrics, pareto_data, filters, cogs_configured_count,
 *   total_skus, product_journey, market_basket, initial_search
 *
 * Reads: daily_snapshot_products, products, product_variants (future service).
 * Writes: product_variants.cogs_amount (inline COGS update).
 * Called by:
 *   - GET   /{workspace:slug}/products           → index()
 *   - PATCH /{workspace:slug}/products/{id}/cogs → updateCogs()
 *
 * @see docs/pages/products.md
 * @see docs/planning/backend.md#ProductsDataService
 */
class ProductsController extends Controller
{
    /**
     * Product list view. Returns the full Inertia prop shape expected by Products/Index.tsx.
     * Mock data covers 50 apparel/outdoor SKUs with varied margins, some without COGS set.
     */
    public function index(Request $request): Response
    {
        $params  = $this->validateIndexParams($request);
        $products = $this->mockProducts();

        return Inertia::render('Products/Index', [
            'products'             => $products,
            'metrics'              => $this->mockMetrics($products),
            'pareto_data'          => $this->buildParetoData($products),
            'filters'              => $params,
            'cogs_configured_count' => collect($products)->whereNotNull('cogs')->count(),
            'total_skus'           => count($products),
            'product_journey'      => $this->mockProductJourney($products),
            'market_basket'        => $this->mockMarketBasket($products),
            'initial_search'       => $params['initial_search'] ?? null,
        ]);
    }

    /**
     * Inline COGS upsert — called by the InlineCogs cell in the table.
     *
     * The TSX sends { cogs: number } via router.patch().
     * We apply it to all variants of this product (flat override, no date-ranging in v1).
     * Per docs/pages/products.md: this does NOT retroactively restate historical COGS.
     * A Toast on save says "New COGS applies to orders from today forward. [Backfill historical]".
     */
    public function updateCogs(Request $request, string $workspace, int $product): RedirectResponse
    {
        $request->validate([
            'cogs' => ['required', 'numeric', 'min:0'],
        ]);

        // Service will write product_variants.cogs_amount here in v1.
        // For now: no-op OK — the frontend uses optimistic UI.
        return back()->with('success', 'COGS updated. New COGS applies to orders from today forward.');
    }

    // ─── Private helpers ──────────────────────────────────────────────────────

    /** @return array<string, mixed> */
    private function validateIndexParams(Request $request): array
    {
        $v = $request->validate([
            'from'        => ['sometimes', 'nullable', 'date_format:Y-m-d'],
            'to'          => ['sometimes', 'nullable', 'date_format:Y-m-d'],
            'country'     => ['sometimes', 'nullable', 'string', 'max:3'],
            'channel'     => ['sometimes', 'nullable', 'string', 'max:80'],
            'sort'        => ['sometimes', 'nullable', 'in:revenue,margin,velocity,orders,units,name,aov,repeat_rate'],
            'stock_alert' => ['sometimes', 'nullable', 'in:7,30'],
            'search'      => ['sometimes', 'nullable', 'string', 'max:255'],
        ]);

        return [
            'from'           => $v['from']        ?? now()->subDays(27)->toDateString(),
            'to'             => $v['to']          ?? now()->toDateString(),
            'country'        => $v['country']     ?? null,
            'channel'        => $v['channel']     ?? null,
            'sort'           => $v['sort']        ?? 'revenue',
            'stock_alert'    => isset($v['stock_alert']) ? (int) $v['stock_alert'] : null,
            'initial_search' => $v['search']      ?? null,
        ];
    }

    /**
     * Compute summary metrics from the products array.
     *
     * @param  array<int, array<string, mixed>> $products
     * @return array<string, mixed>
     */
    private function mockMetrics(array $products): array
    {
        $withCogs   = array_filter($products, fn ($p) => $p['cogs'] !== null);
        $margins    = array_map(fn ($p) => $p['margin_pct'], $withCogs);
        $velocities = array_filter(array_map(fn ($p) => $p['velocity'], $products));

        sort($margins);
        sort($velocities);

        $median = fn (array $arr) => count($arr) > 0
            ? (count($arr) % 2 === 0
                ? ($arr[count($arr) / 2 - 1] + $arr[count($arr) / 2]) / 2
                : $arr[(int) (count($arr) / 2)])
            : null;

        $revenues = array_column($products, 'revenue');
        arsort($revenues);
        $totalRev = array_sum($revenues);
        $top10    = array_sum(array_slice($revenues, 0, 10));
        $top10pct = $totalRev > 0 ? round($top10 / $totalRev * 100, 1) : null;

        $velocityArr = array_values($velocities);
        sort($velocityArr);

        return [
            'products_sold'         => count($products),
            'top10_concentration'   => $top10pct,
            'median_gross_margin'   => $median(array_values($margins)),
            'velocity_mean'         => count($velocityArr) > 0 ? round(array_sum($velocityArr) / count($velocityArr), 2) : null,
            'velocity_median'       => $median($velocityArr),
            'velocity_mode'         => count($velocityArr) > 0 ? $velocityArr[0] : null,
        ];
    }

    /**
     * Build Pareto data (revenue DESC, cumulative %) for the Pareto chart.
     *
     * @param  array<int, array<string, mixed>> $products
     * @return array<int, array<string, mixed>>
     */
    private function buildParetoData(array $products): array
    {
        $sorted = collect($products)
            ->sortByDesc('revenue')
            ->values();

        $total = $sorted->sum('revenue') ?: 1;
        $cum   = 0.0;

        return $sorted->map(function ($p, $i) use ($total, &$cum) {
            $cum += $p['revenue'] / $total * 100;
            return [
                'rank'           => $i + 1,
                'name'           => $p['name'],
                'revenue'        => $p['revenue'],
                'cumulative_pct' => round($cum, 2),
            ];
        })->values()->all();
    }

    /**
     * Product journey mock — which SKU appears as 1st / 2nd / 3rd purchase.
     *
     * @param  array<int, array<string, mixed>> $products
     * @return array<int, array<string, mixed>>
     */
    private function mockProductJourney(array $products): array
    {
        return collect($products)
            ->take(12)
            ->map(fn ($p, $i) => [
                'product_external_id' => $p['external_id'],
                'product_name'        => $p['name'],
                'as_first'            => max(0, (int) round($p['orders'] * 0.62)),
                'as_second'           => max(0, (int) round($p['orders'] * 0.22)),
                'as_third'            => max(0, (int) round($p['orders'] * 0.10)),
            ])
            ->values()
            ->all();
    }

    /**
     * Market basket mock — frequently bought together pairs.
     *
     * @param  array<int, array<string, mixed>> $products
     * @return array<int, array<string, mixed>>
     */
    private function mockMarketBasket(array $products): array
    {
        $pairs = [];
        $slice = array_slice($products, 0, 8);
        for ($i = 0; $i < count($slice) - 1; $i++) {
            for ($j = $i + 1; $j < count($slice); $j++) {
                $pairs[] = [
                    'product_a_id'      => $slice[$i]['external_id'],
                    'product_a'         => $slice[$i]['name'],
                    'product_b_id'      => $slice[$j]['external_id'],
                    'product_b'         => $slice[$j]['name'],
                    'co_purchase_count' => rand(8, 84),
                    'lift_pct'          => round(rand(30, 180) / 10, 1),
                ];
            }
        }
        // Limit to 10 pairs sorted by co_purchase_count DESC
        usort($pairs, fn ($a, $b) => $b['co_purchase_count'] - $a['co_purchase_count']);
        return array_slice($pairs, 0, 10);
    }

    /**
     * 50 apparel/outdoor mock products.
     * Margins range 0–80 %, some with null COGS, variants for ~30 %.
     * Primary source is always 'store' (ground truth for product sales per products.md).
     *
     * @return array<int, array<string, mixed>>
     */
    private function mockProducts(): array
    {
        // Helper: generate a 7-point velocity sparkline centred around $mean.
        $spark = fn (float $mean) => array_map(
            fn () => max(0.0, round($mean + (rand(-15, 15) / 10) * $mean * 0.3, 2)),
            range(0, 6),
        );

        return [
            // ── Crewnecks & Tops ──────────────────────────────────────────────
            [
                'id'               => 1,
                'external_id'      => 'prod_01HWQA1',
                'name'             => 'Merino Wool Crewneck',
                'thumbnail_url'    => null,
                'sku'              => 'SHIRT-MW-CRW-NVY',
                'units'            => 312,
                'revenue'          => 24336.00,
                'orders'           => 298,
                'aov'              => 81.66,
                'cogs'             => 22.50,
                'margin_pct'       => 71.2,
                'velocity'         => 11.14,
                'velocity_sparkline' => $spark(11.14),
                'label'            => 'rockstar',
                'sources'          => ['store', 'real', 'facebook'],
                'days_of_cover'    => 4.2,
                'views'            => 4820,
                'view_cvr'         => 0.065,
                'add_to_cart_rate' => 0.14,
                'top_campaigns'    => ['Summer Wool Launch', 'Brand – Prospecting'],
                'repeat_rate'      => 0.38,
            ],
            [
                'id'               => 2,
                'external_id'      => 'prod_01HWQA2',
                'name'             => 'Organic Cotton Henley',
                'thumbnail_url'    => null,
                'sku'              => 'SHIRT-OC-HEN-WHT',
                'units'            => 189,
                'revenue'          => 12096.00,
                'orders'           => 184,
                'aov'              => 65.74,
                'cogs'             => null,
                'margin_pct'       => null,
                'velocity'         => 6.75,
                'velocity_sparkline' => $spark(6.75),
                'label'            => null,
                'sources'          => ['store', 'real'],
                'days_of_cover'    => 12.1,
                'views'            => 2340,
                'view_cvr'         => 0.079,
                'add_to_cart_rate' => 0.18,
                'top_campaigns'    => [],
                'repeat_rate'      => 0.22,
            ],
            [
                'id'               => 3,
                'external_id'      => 'prod_01HWQA3',
                'name'             => 'Linen Camp-Collar Shirt',
                'thumbnail_url'    => null,
                'sku'              => 'SHIRT-LN-CMP-SAG',
                'units'            => 134,
                'revenue'          => 12328.00,
                'orders'           => 127,
                'aov'              => 97.07,
                'cogs'             => 18.00,
                'margin_pct'       => 80.4,
                'velocity'         => 4.79,
                'velocity_sparkline' => $spark(4.79),
                'label'            => 'hot',
                'sources'          => ['store', 'real', 'google'],
                'days_of_cover'    => 6.5,
                'views'            => 1920,
                'view_cvr'         => 0.066,
                'add_to_cart_rate' => 0.12,
                'top_campaigns'    => ['Summer Linen Drop'],
                'repeat_rate'      => 0.19,
            ],
            [
                'id'               => 4,
                'external_id'      => 'prod_01HWQA4',
                'name'             => 'Recycled Fleece Quarter-Zip',
                'thumbnail_url'    => null,
                'sku'              => 'TOP-RFC-QZ-GRY',
                'units'            => 98,
                'revenue'          => 8624.00,
                'orders'           => 94,
                'aov'              => 91.74,
                'cogs'             => 29.00,
                'margin_pct'       => 67.1,
                'velocity'         => 3.50,
                'velocity_sparkline' => $spark(3.50),
                'label'            => null,
                'sources'          => ['store', 'real'],
                'days_of_cover'    => 5.4,
                'views'            => 1100,
                'view_cvr'         => 0.086,
                'add_to_cart_rate' => 0.19,
                'top_campaigns'    => [],
                'repeat_rate'      => 0.14,
            ],
            [
                'id'               => 5,
                'external_id'      => 'prod_01HWQA5',
                'name'             => 'Bamboo Running Shorts',
                'thumbnail_url'    => null,
                'sku'              => 'SHORT-BAM-RUN-BLK',
                'units'            => 512,
                'revenue'          => 18432.00,
                'orders'           => 498,
                'aov'              => 37.01,
                'cogs'             => 9.50,
                'margin_pct'       => 73.6,
                'velocity'         => 18.29,
                'velocity_sparkline' => $spark(18.29),
                'label'            => 'rockstar',
                'sources'          => ['store', 'real', 'facebook', 'google'],
                'days_of_cover'    => 7.9,
                'views'            => 8640,
                'view_cvr'         => 0.058,
                'add_to_cart_rate' => 0.16,
                'top_campaigns'    => ['Running – Q2', 'Summer Basics'],
                'repeat_rate'      => 0.44,
            ],
            // ── Outerwear ──────────────────────────────────────────────────────
            [
                'id'               => 6,
                'external_id'      => 'prod_01HWQA6',
                'name'             => 'Alpine Shell Jacket',
                'thumbnail_url'    => null,
                'sku'              => 'JKT-ALP-SHL-OLV',
                'units'            => 78,
                'revenue'          => 19422.00,
                'orders'           => 75,
                'aov'              => 259.0,
                'cogs'             => 84.00,
                'margin_pct'       => 66.3,
                'velocity'         => 2.79,
                'velocity_sparkline' => $spark(2.79),
                'label'            => null,
                'sources'          => ['store', 'real', 'facebook'],
                'days_of_cover'    => 7.9,
                'views'            => 2200,
                'view_cvr'         => 0.034,
                'add_to_cart_rate' => 0.09,
                'top_campaigns'    => ['Alpine – Prospecting'],
                'repeat_rate'      => 0.11,
            ],
            [
                'id'               => 7,
                'external_id'      => 'prod_01HWQA7',
                'name'             => 'Softshell Wind Jacket',
                'thumbnail_url'    => null,
                'sku'              => 'JKT-SFT-WND-BLU',
                'units'            => 54,
                'revenue'          => 9612.00,
                'orders'           => 52,
                'aov'              => 184.85,
                'cogs'             => null,
                'margin_pct'       => null,
                'velocity'         => 1.93,
                'velocity_sparkline' => $spark(1.93),
                'label'            => null,
                'sources'          => ['store', 'real'],
                'days_of_cover'    => 19.7,
                'views'            => 1560,
                'view_cvr'         => 0.033,
                'add_to_cart_rate' => 0.08,
                'top_campaigns'    => [],
                'repeat_rate'      => null,
            ],
            [
                'id'               => 8,
                'external_id'      => 'prod_01HWQA8',
                'name'             => 'Merino Hooded Midlayer',
                'thumbnail_url'    => null,
                'sku'              => 'MID-MW-HOOD-CHR',
                'units'            => 67,
                'revenue'          => 9916.00,
                'orders'           => 65,
                'aov'              => 152.55,
                'cogs'             => 45.00,
                'margin_pct'       => 69.5,
                'velocity'         => 2.39,
                'velocity_sparkline' => $spark(2.39),
                'label'            => 'at_risk',
                'sources'          => ['store', 'real'],
                'days_of_cover'    => 4.6,
                'views'            => 1340,
                'view_cvr'         => 0.049,
                'add_to_cart_rate' => 0.11,
                'top_campaigns'    => [],
                'repeat_rate'      => 0.08,
            ],
            [
                'id'               => 9,
                'external_id'      => 'prod_01HWQA9',
                'name'             => 'Packable Down Vest',
                'thumbnail_url'    => null,
                'sku'              => 'VEST-DOWN-PCK-NVY',
                'units'            => 44,
                'revenue'          => 5192.00,
                'orders'           => 43,
                'aov'              => 120.74,
                'cogs'             => 38.00,
                'margin_pct'       => 67.8,
                'velocity'         => 1.57,
                'velocity_sparkline' => $spark(1.57),
                'label'            => 'cold',
                'sources'          => ['store', 'real'],
                'days_of_cover'    => 36.9,
                'views'            => 940,
                'view_cvr'         => 0.046,
                'add_to_cart_rate' => 0.10,
                'top_campaigns'    => [],
                'repeat_rate'      => null,
            ],
            [
                'id'               => 10,
                'external_id'      => 'prod_01HWQA10',
                'name'             => 'Insulated Puffer Parka',
                'thumbnail_url'    => null,
                'sku'              => 'PARKA-INS-BLK-2XL',
                'units'            => 29,
                'revenue'          => 8990.00,
                'orders'           => 28,
                'aov'              => 321.07,
                'cogs'             => null,
                'margin_pct'       => null,
                'velocity'         => 1.04,
                'velocity_sparkline' => $spark(1.04),
                'label'            => null,
                'sources'          => ['store', 'real'],
                'days_of_cover'    => 13.5,
                'views'            => 820,
                'view_cvr'         => 0.034,
                'add_to_cart_rate' => 0.07,
                'top_campaigns'    => [],
                'repeat_rate'      => null,
            ],
            // ── Footwear ──────────────────────────────────────────────────────
            [
                'id'               => 11,
                'external_id'      => 'prod_01HWQA11',
                'name'             => 'Trail Runner Low V2',
                'thumbnail_url'    => null,
                'sku'              => 'SHOE-TRL-LOW-V2-GRY',
                'units'            => 156,
                'revenue'          => 21060.00,
                'orders'           => 148,
                'aov'              => 142.30,
                'cogs'             => 42.00,
                'margin_pct'       => 68.9,
                'velocity'         => 5.57,
                'velocity_sparkline' => $spark(5.57),
                'label'            => 'rockstar',
                'sources'          => ['store', 'real', 'facebook', 'google'],
                'days_of_cover'    => 11.1,
                'views'            => 5200,
                'view_cvr'         => 0.028,
                'add_to_cart_rate' => 0.09,
                'top_campaigns'    => ['Trail Running – Q2', 'Retargeting – Shoes'],
                'repeat_rate'      => 0.28,
            ],
            [
                'id'               => 12,
                'external_id'      => 'prod_01HWQA12',
                'name'             => 'Hiking Boot Waterproof',
                'thumbnail_url'    => null,
                'sku'              => 'BOOT-HIK-WP-TAN',
                'units'            => 88,
                'revenue'          => 14784.00,
                'orders'           => 84,
                'aov'              => 176.0,
                'cogs'             => 58.00,
                'margin_pct'       => 65.5,
                'velocity'         => 3.14,
                'velocity_sparkline' => $spark(3.14),
                'label'            => null,
                'sources'          => ['store', 'real'],
                'days_of_cover'    => 10.8,
                'views'            => 3100,
                'view_cvr'         => 0.027,
                'add_to_cart_rate' => 0.08,
                'top_campaigns'    => [],
                'repeat_rate'      => 0.15,
            ],
            [
                'id'               => 13,
                'external_id'      => 'prod_01HWQA13',
                'name'             => 'Camp Moc Slipper',
                'thumbnail_url'    => null,
                'sku'              => 'SLIPPER-CMP-MOC-BRN',
                'units'            => 224,
                'revenue'          => 9856.00,
                'orders'           => 218,
                'aov'              => 45.21,
                'cogs'             => 12.00,
                'margin_pct'       => 72.8,
                'velocity'         => 8.0,
                'velocity_sparkline' => $spark(8.0),
                'label'            => 'hot',
                'sources'          => ['store', 'real'],
                'days_of_cover'    => 12.3,
                'views'            => 3800,
                'view_cvr'         => 0.057,
                'add_to_cart_rate' => 0.15,
                'top_campaigns'    => [],
                'repeat_rate'      => 0.32,
            ],
            [
                'id'               => 14,
                'external_id'      => 'prod_01HWQA14',
                'name'             => 'Minimalist Road Shoe',
                'thumbnail_url'    => null,
                'sku'              => 'SHOE-MIN-ROAD-BLK',
                'units'            => 61,
                'revenue'          => 7259.00,
                'orders'           => 58,
                'aov'              => 125.15,
                'cogs'             => null,
                'margin_pct'       => null,
                'velocity'         => 2.18,
                'velocity_sparkline' => $spark(2.18),
                'label'            => 'cold',
                'sources'          => ['store', 'real'],
                'days_of_cover'    => 12.4,
                'views'            => 2100,
                'view_cvr'         => 0.028,
                'add_to_cart_rate' => 0.07,
                'top_campaigns'    => [],
                'repeat_rate'      => null,
            ],
            // ── Accessories ──────────────────────────────────────────────────
            [
                'id'               => 15,
                'external_id'      => 'prod_01HWQA15',
                'name'             => 'Merino Beanie',
                'thumbnail_url'    => null,
                'sku'              => 'HAT-MW-BEAN-CHAR',
                'units'            => 418,
                'revenue'          => 11704.00,
                'orders'           => 408,
                'aov'              => 28.69,
                'cogs'             => 6.50,
                'margin_pct'       => 76.8,
                'velocity'         => 14.93,
                'velocity_sparkline' => $spark(14.93),
                'label'            => 'rockstar',
                'sources'          => ['store', 'real'],
                'days_of_cover'    => 14.2,
                'views'            => 5600,
                'view_cvr'         => 0.073,
                'add_to_cart_rate' => 0.20,
                'top_campaigns'    => [],
                'repeat_rate'      => 0.42,
            ],
            [
                'id'               => 16,
                'external_id'      => 'prod_01HWQA16',
                'name'             => 'Trail Running Belt',
                'thumbnail_url'    => null,
                'sku'              => 'ACC-BELT-TRL-RED',
                'units'            => 287,
                'revenue'          => 9184.00,
                'orders'           => 281,
                'aov'              => 32.68,
                'cogs'             => 8.00,
                'margin_pct'       => 75.0,
                'velocity'         => 10.25,
                'velocity_sparkline' => $spark(10.25),
                'label'            => null,
                'sources'          => ['store', 'real'],
                'days_of_cover'    => 15.2,
                'views'            => 3900,
                'view_cvr'         => 0.072,
                'add_to_cart_rate' => 0.18,
                'top_campaigns'    => [],
                'repeat_rate'      => 0.24,
            ],
            [
                'id'               => 17,
                'external_id'      => 'prod_01HWQA17',
                'name'             => 'Bamboo Crew Socks 3-Pack',
                'thumbnail_url'    => null,
                'sku'              => 'SOCKS-BAM-3PK-WHT',
                'units'            => 634,
                'revenue'          => 11412.00,
                'orders'           => 621,
                'aov'              => 18.38,
                'cogs'             => 5.20,
                'margin_pct'       => 71.1,
                'velocity'         => 22.64,
                'velocity_sparkline' => $spark(22.64),
                'label'            => null,
                'sources'          => ['store', 'real'],
                'days_of_cover'    => 21.2,
                'views'            => 6800,
                'view_cvr'         => 0.091,
                'add_to_cart_rate' => 0.24,
                'top_campaigns'    => [],
                'repeat_rate'      => 0.55,
            ],
            [
                'id'               => 18,
                'external_id'      => 'prod_01HWQA18',
                'name'             => 'Merino Glove Liner',
                'thumbnail_url'    => null,
                'sku'              => 'GLOVE-MW-LINER-BLK',
                'units'            => 112,
                'revenue'          => 2688.00,
                'orders'           => 110,
                'aov'              => 24.44,
                'cogs'             => null,
                'margin_pct'       => null,
                'velocity'         => 4.0,
                'velocity_sparkline' => $spark(4.0),
                'label'            => 'cold',
                'sources'          => ['store', 'real'],
                'days_of_cover'    => 16.8,
                'views'            => 1480,
                'view_cvr'         => 0.074,
                'add_to_cart_rate' => 0.18,
                'top_campaigns'    => [],
                'repeat_rate'      => null,
            ],
            [
                'id'               => 19,
                'external_id'      => 'prod_01HWQA19',
                'name'             => 'Hydration Vest 8L',
                'thumbnail_url'    => null,
                'sku'              => 'GEAR-HVST-8L-BLU',
                'units'            => 94,
                'revenue'          => 8366.00,
                'orders'           => 92,
                'aov'              => 90.93,
                'cogs'             => 28.00,
                'margin_pct'       => 68.5,
                'velocity'         => 3.36,
                'velocity_sparkline' => $spark(3.36),
                'label'            => null,
                'sources'          => ['store', 'real'],
                'days_of_cover'    => 14.3,
                'views'            => 2200,
                'view_cvr'         => 0.042,
                'add_to_cart_rate' => 0.11,
                'top_campaigns'    => [],
                'repeat_rate'      => 0.12,
            ],
            [
                'id'               => 20,
                'external_id'      => 'prod_01HWQA20',
                'name'             => 'Trekking Pole Set',
                'thumbnail_url'    => null,
                'sku'              => 'GEAR-POLE-SET-BLK',
                'units'            => 38,
                'revenue'          => 2736.00,
                'orders'           => 37,
                'aov'              => 74.0,
                'cogs'             => null,
                'margin_pct'       => null,
                'velocity'         => 1.36,
                'velocity_sparkline' => $spark(1.36),
                'label'            => null,
                'sources'          => ['store', 'real'],
                'days_of_cover'    => 21.3,
                'views'            => 780,
                'view_cvr'         => 0.047,
                'add_to_cart_rate' => 0.10,
                'top_campaigns'    => [],
                'repeat_rate'      => null,
            ],
            // ── Low-margin / at-risk ────────────────────────────────────────
            [
                'id'               => 21,
                'external_id'      => 'prod_01HWQA21',
                'name'             => 'Compression Calf Sleeve',
                'thumbnail_url'    => null,
                'sku'              => 'ACC-COMP-CALF-BLK',
                'units'            => 167,
                'revenue'          => 3674.00,
                'orders'           => 164,
                'aov'              => 22.40,
                'cogs'             => 9.80,
                'margin_pct'       => 28.3,
                'velocity'         => 5.96,
                'velocity_sparkline' => $spark(5.96),
                'label'            => 'at_risk',
                'sources'          => ['store', 'real'],
                'days_of_cover'    => 13.8,
                'views'            => 2100,
                'view_cvr'         => 0.078,
                'add_to_cart_rate' => 0.17,
                'top_campaigns'    => [],
                'repeat_rate'      => 0.09,
            ],
            [
                'id'               => 22,
                'external_id'      => 'prod_01HWQA22',
                'name'             => 'Foam Roller 60cm',
                'thumbnail_url'    => null,
                'sku'              => 'GEAR-FOAM-60-BLK',
                'units'            => 88,
                'revenue'          => 2992.00,
                'orders'           => 86,
                'aov'              => 34.79,
                'cogs'             => 14.00,
                'margin_pct'       => 58.8,
                'velocity'         => 3.14,
                'velocity_sparkline' => $spark(3.14),
                'label'            => null,
                'sources'          => ['store', 'real'],
                'days_of_cover'    => 17.5,
                'views'            => 1220,
                'view_cvr'         => 0.071,
                'add_to_cart_rate' => 0.16,
                'top_campaigns'    => [],
                'repeat_rate'      => 0.16,
            ],
            [
                'id'               => 23,
                'external_id'      => 'prod_01HWQA23',
                'name'             => 'Resistance Band Set',
                'thumbnail_url'    => null,
                'sku'              => 'GEAR-RBAND-SET-MLT',
                'units'            => 214,
                'revenue'          => 4066.00,
                'orders'           => 210,
                'aov'              => 19.36,
                'cogs'             => 6.50,
                'margin_pct'       => 65.8,
                'velocity'         => 7.64,
                'velocity_sparkline' => $spark(7.64),
                'label'            => null,
                'sources'          => ['store', 'real'],
                'days_of_cover'    => 40.6,
                'views'            => 2800,
                'view_cvr'         => 0.075,
                'add_to_cart_rate' => 0.19,
                'top_campaigns'    => [],
                'repeat_rate'      => 0.26,
            ],
            [
                'id'               => 24,
                'external_id'      => 'prod_01HWQA24',
                'name'             => 'Yoga Mat 6mm',
                'thumbnail_url'    => null,
                'sku'              => 'GEAR-YOGA-6MM-PUR',
                'units'            => 72,
                'revenue'          => 3888.00,
                'orders'           => 70,
                'aov'              => 55.54,
                'cogs'             => null,
                'margin_pct'       => null,
                'velocity'         => 2.57,
                'velocity_sparkline' => $spark(2.57),
                'label'            => null,
                'sources'          => ['store', 'real'],
                'days_of_cover'    => 17.1,
                'views'            => 1640,
                'view_cvr'         => 0.043,
                'add_to_cart_rate' => 0.10,
                'top_campaigns'    => [],
                'repeat_rate'      => null,
            ],
            [
                'id'               => 25,
                'external_id'      => 'prod_01HWQA25',
                'name'             => 'Carabiner 3-Pack',
                'thumbnail_url'    => null,
                'sku'              => 'GEAR-CARA-3PK-SLV',
                'units'            => 312,
                'revenue'          => 4368.00,
                'orders'           => 306,
                'aov'              => 14.27,
                'cogs'             => 3.20,
                'margin_pct'       => 77.1,
                'velocity'         => 11.14,
                'velocity_sparkline' => $spark(11.14),
                'label'            => null,
                'sources'          => ['store', 'real'],
                'days_of_cover'    => 75.5,
                'views'            => 3800,
                'view_cvr'         => 0.081,
                'add_to_cart_rate' => 0.22,
                'top_campaigns'    => [],
                'repeat_rate'      => 0.48,
            ],
            [
                'id'               => 26,
                'external_id'      => 'prod_01HWQA26',
                'name'             => 'Waterproof Dry Bag 10L',
                'thumbnail_url'    => null,
                'sku'              => 'GEAR-DRYBAG-10L-YLW',
                'units'            => 98,
                'revenue'          => 2744.00,
                'orders'           => 96,
                'aov'              => 28.58,
                'cogs'             => 16.00,
                'margin_pct'       => 42.9,
                'velocity'         => 3.50,
                'velocity_sparkline' => $spark(3.50),
                'label'            => null,
                'sources'          => ['store', 'real'],
                'days_of_cover'    => 20.6,
                'views'            => 1420,
                'view_cvr'         => 0.068,
                'add_to_cart_rate' => 0.15,
                'top_campaigns'    => [],
                'repeat_rate'      => 0.13,
            ],
            [
                'id'               => 27,
                'external_id'      => 'prod_01HWQA27',
                'name'             => 'Trekking Gaiters',
                'thumbnail_url'    => null,
                'sku'              => 'GEAR-GAITR-LOW-GRN',
                'units'            => 44,
                'revenue'          => 2112.00,
                'orders'           => 43,
                'aov'              => 49.12,
                'cogs'             => 22.00,
                'margin_pct'       => 54.2,
                'velocity'         => 1.57,
                'velocity_sparkline' => $spark(1.57),
                'label'            => null,
                'sources'          => ['store', 'real'],
                'days_of_cover'    => 18.5,
                'views'            => 780,
                'view_cvr'         => 0.055,
                'add_to_cart_rate' => 0.12,
                'top_campaigns'    => [],
                'repeat_rate'      => null,
            ],
            [
                'id'               => 28,
                'external_id'      => 'prod_01HWQA28',
                'name'             => 'Fleece Neck Gaiter',
                'thumbnail_url'    => null,
                'sku'              => 'ACC-GAITER-FLC-BLK',
                'units'            => 196,
                'revenue'          => 4312.00,
                'orders'           => 192,
                'aov'              => 22.46,
                'cogs'             => null,
                'margin_pct'       => null,
                'velocity'         => 7.0,
                'velocity_sparkline' => $spark(7.0),
                'label'            => null,
                'sources'          => ['store', 'real'],
                'days_of_cover'    => 17.7,
                'views'            => 2200,
                'view_cvr'         => 0.087,
                'add_to_cart_rate' => 0.21,
                'top_campaigns'    => [],
                'repeat_rate'      => 0.20,
            ],
            [
                'id'               => 29,
                'external_id'      => 'prod_01HWQA29',
                'name'             => 'Alpine Sunglasses',
                'thumbnail_url'    => null,
                'sku'              => 'ACC-SUNG-ALP-BRN',
                'units'            => 82,
                'revenue'          => 4756.00,
                'orders'           => 80,
                'aov'              => 59.45,
                'cogs'             => 18.00,
                'margin_pct'       => 68.9,
                'velocity'         => 2.93,
                'velocity_sparkline' => $spark(2.93),
                'label'            => 'hot',
                'sources'          => ['store', 'real', 'google'],
                'days_of_cover'    => 16.4,
                'views'            => 2400,
                'view_cvr'         => 0.033,
                'add_to_cart_rate' => 0.09,
                'top_campaigns'    => ['Summer Accessories'],
                'repeat_rate'      => 0.14,
            ],
            [
                'id'               => 30,
                'external_id'      => 'prod_01HWQA30',
                'name'             => 'Bouldering Chalk Bag',
                'thumbnail_url'    => null,
                'sku'              => 'GEAR-CHALK-BAG-RED',
                'units'            => 148,
                'revenue'          => 3552.00,
                'orders'           => 145,
                'aov'              => 24.50,
                'cogs'             => 7.00,
                'margin_pct'       => 70.8,
                'velocity'         => 5.29,
                'velocity_sparkline' => $spark(5.29),
                'label'            => null,
                'sources'          => ['store', 'real'],
                'days_of_cover'    => 18.1,
                'views'            => 2000,
                'view_cvr'         => 0.073,
                'add_to_cart_rate' => 0.19,
                'top_campaigns'    => [],
                'repeat_rate'      => 0.30,
            ],
            [
                'id'               => 31,
                'external_id'      => 'prod_01HWQA31',
                'name'             => 'Merino Base Layer Bottom',
                'thumbnail_url'    => null,
                'sku'              => 'BASE-MW-BTM-GRY',
                'units'            => 112,
                'revenue'          => 8064.00,
                'orders'           => 109,
                'aov'              => 73.98,
                'cogs'             => 24.00,
                'margin_pct'       => 66.7,
                'velocity'         => 4.0,
                'velocity_sparkline' => $spark(4.0),
                'label'            => null,
                'sources'          => ['store', 'real'],
                'days_of_cover'    => 14.0,
                'views'            => 1980,
                'view_cvr'         => 0.055,
                'add_to_cart_rate' => 0.13,
                'top_campaigns'    => [],
                'repeat_rate'      => 0.18,
            ],
            [
                'id'               => 32,
                'external_id'      => 'prod_01HWQA32',
                'name'             => 'Merino Base Layer Top',
                'thumbnail_url'    => null,
                'sku'              => 'BASE-MW-TOP-GRY',
                'units'            => 124,
                'revenue'          => 8432.00,
                'orders'           => 121,
                'aov'              => 69.69,
                'cogs'             => 22.00,
                'margin_pct'       => 67.6,
                'velocity'         => 4.43,
                'velocity_sparkline' => $spark(4.43),
                'label'            => null,
                'sources'          => ['store', 'real'],
                'days_of_cover'    => 13.8,
                'views'            => 2100,
                'view_cvr'         => 0.058,
                'add_to_cart_rate' => 0.14,
                'top_campaigns'    => [],
                'repeat_rate'      => 0.20,
            ],
            [
                'id'               => 33,
                'external_id'      => 'prod_01HWQA33',
                'name'             => 'Cotton Pocket Tee',
                'thumbnail_url'    => null,
                'sku'              => 'TEE-CTN-PCKT-WHT',
                'units'            => 342,
                'revenue'          => 9576.00,
                'orders'           => 335,
                'aov'              => 28.59,
                'cogs'             => 7.00,
                'margin_pct'       => 75.0,
                'velocity'         => 12.21,
                'velocity_sparkline' => $spark(12.21),
                'label'            => null,
                'sources'          => ['store', 'real'],
                'days_of_cover'    => 17.9,
                'views'            => 4600,
                'view_cvr'         => 0.073,
                'add_to_cart_rate' => 0.20,
                'top_campaigns'    => [],
                'repeat_rate'      => 0.36,
            ],
            [
                'id'               => 34,
                'external_id'      => 'prod_01HWQA34',
                'name'             => 'Jogger Sweatpant',
                'thumbnail_url'    => null,
                'sku'              => 'PANT-JOG-FLC-NAV',
                'units'            => 88,
                'revenue'          => 5632.00,
                'orders'           => 86,
                'aov'              => 65.49,
                'cogs'             => null,
                'margin_pct'       => null,
                'velocity'         => 3.14,
                'velocity_sparkline' => $spark(3.14),
                'label'            => null,
                'sources'          => ['store', 'real'],
                'days_of_cover'    => 13.4,
                'views'            => 1800,
                'view_cvr'         => 0.048,
                'add_to_cart_rate' => 0.11,
                'top_campaigns'    => [],
                'repeat_rate'      => null,
            ],
            [
                'id'               => 35,
                'external_id'      => 'prod_01HWQA35',
                'name'             => 'Relaxed Linen Trousers',
                'thumbnail_url'    => null,
                'sku'              => 'PANT-LN-RLX-KHK',
                'units'            => 62,
                'revenue'          => 5456.00,
                'orders'           => 60,
                'aov'              => 90.93,
                'cogs'             => 20.00,
                'margin_pct'       => 77.3,
                'velocity'         => 2.21,
                'velocity_sparkline' => $spark(2.21),
                'label'            => 'hot',
                'sources'          => ['store', 'real'],
                'days_of_cover'    => 12.7,
                'views'            => 1400,
                'view_cvr'         => 0.043,
                'add_to_cart_rate' => 0.10,
                'top_campaigns'    => [],
                'repeat_rate'      => 0.12,
            ],
            [
                'id'               => 36,
                'external_id'      => 'prod_01HWQA36',
                'name'             => 'Synthetic Sleeping Bag 0°C',
                'thumbnail_url'    => null,
                'sku'              => 'GEAR-SLPBG-0C-RED',
                'units'            => 18,
                'revenue'          => 1764.00,
                'orders'           => 17,
                'aov'              => 103.76,
                'cogs'             => 52.00,
                'margin_pct'       => 46.9,
                'velocity'         => 0.64,
                'velocity_sparkline' => $spark(0.64),
                'label'            => 'cold',
                'sources'          => ['store', 'real'],
                'days_of_cover'    => 18.8,
                'views'            => 640,
                'view_cvr'         => 0.027,
                'add_to_cart_rate' => 0.07,
                'top_campaigns'    => [],
                'repeat_rate'      => null,
            ],
            [
                'id'               => 37,
                'external_id'      => 'prod_01HWQA37',
                'name'             => 'Neoprene Swim Gloves',
                'thumbnail_url'    => null,
                'sku'              => 'GEAR-SWMGLV-NEO-BLK',
                'units'            => 42,
                'revenue'          => 1008.00,
                'orders'           => 41,
                'aov'              => 24.59,
                'cogs'             => 11.00,
                'margin_pct'       => 54.2,
                'velocity'         => 1.50,
                'velocity_sparkline' => $spark(1.50),
                'label'            => null,
                'sources'          => ['store', 'real'],
                'days_of_cover'    => 38.7,
                'views'            => 680,
                'view_cvr'         => 0.060,
                'add_to_cart_rate' => 0.14,
                'top_campaigns'    => [],
                'repeat_rate'      => null,
            ],
            [
                'id'               => 38,
                'external_id'      => 'prod_01HWQA38',
                'name'             => 'Insulating Bivvy Bag',
                'thumbnail_url'    => null,
                'sku'              => 'GEAR-BIVVY-INS-SLV',
                'units'            => 22,
                'revenue'          => 968.00,
                'orders'           => 21,
                'aov'              => 46.10,
                'cogs'             => null,
                'margin_pct'       => null,
                'velocity'         => 0.79,
                'velocity_sparkline' => $spark(0.79),
                'label'            => null,
                'sources'          => ['store', 'real'],
                'days_of_cover'    => 22.8,
                'views'            => 480,
                'view_cvr'         => 0.044,
                'add_to_cart_rate' => 0.09,
                'top_campaigns'    => [],
                'repeat_rate'      => null,
            ],
            [
                'id'               => 39,
                'external_id'      => 'prod_01HWQA39',
                'name'             => 'Printed Muscle Tank',
                'thumbnail_url'    => null,
                'sku'              => 'TOP-TANK-PRNT-WHT',
                'units'            => 388,
                'revenue'          => 12416.00,
                'orders'           => 380,
                'aov'              => 32.67,
                'cogs'             => 7.50,
                'margin_pct'       => 76.6,
                'velocity'         => 13.86,
                'velocity_sparkline' => $spark(13.86),
                'label'            => null,
                'sources'          => ['store', 'real'],
                'days_of_cover'    => 14.1,
                'views'            => 5200,
                'view_cvr'         => 0.073,
                'add_to_cart_rate' => 0.21,
                'top_campaigns'    => [],
                'repeat_rate'      => 0.33,
            ],
            [
                'id'               => 40,
                'external_id'      => 'prod_01HWQA40',
                'name'             => 'Cropped Windbreaker',
                'thumbnail_url'    => null,
                'sku'              => 'JKT-CRPD-WIND-PNK',
                'units'            => 68,
                'revenue'          => 6664.00,
                'orders'           => 66,
                'aov'              => 100.97,
                'cogs'             => 26.00,
                'margin_pct'       => 73.5,
                'velocity'         => 2.43,
                'velocity_sparkline' => $spark(2.43),
                'label'            => 'hot',
                'sources'          => ['store', 'real', 'facebook'],
                'days_of_cover'    => 14.0,
                'views'            => 1820,
                'view_cvr'         => 0.036,
                'add_to_cart_rate' => 0.10,
                'top_campaigns'    => ['Spring Outerwear Drop'],
                'repeat_rate'      => 0.13,
            ],
            [
                'id'               => 41,
                'external_id'      => 'prod_01HWQA41',
                'name'             => 'Denim Overshirt',
                'thumbnail_url'    => null,
                'sku'              => 'SHIRT-DNM-OVER-IND',
                'units'            => 52,
                'revenue'          => 4888.00,
                'orders'           => 51,
                'aov'              => 95.84,
                'cogs'             => 28.00,
                'margin_pct'       => 70.2,
                'velocity'         => 1.86,
                'velocity_sparkline' => $spark(1.86),
                'label'            => null,
                'sources'          => ['store', 'real'],
                'days_of_cover'    => 11.8,
                'views'            => 1140,
                'view_cvr'         => 0.045,
                'add_to_cart_rate' => 0.11,
                'top_campaigns'    => [],
                'repeat_rate'      => 0.10,
            ],
            [
                'id'               => 42,
                'external_id'      => 'prod_01HWQA42',
                'name'             => 'Stretch Chino',
                'thumbnail_url'    => null,
                'sku'              => 'PANT-CHNO-STR-BEG',
                'units'            => 78,
                'revenue'          => 5772.00,
                'orders'           => 76,
                'aov'              => 75.95,
                'cogs'             => 22.00,
                'margin_pct'       => 70.3,
                'velocity'         => 2.79,
                'velocity_sparkline' => $spark(2.79),
                'label'            => null,
                'sources'          => ['store', 'real'],
                'days_of_cover'    => 13.6,
                'views'            => 1640,
                'view_cvr'         => 0.046,
                'add_to_cart_rate' => 0.12,
                'top_campaigns'    => [],
                'repeat_rate'      => 0.14,
            ],
            [
                'id'               => 43,
                'external_id'      => 'prod_01HWQA43',
                'name'             => 'Sun Hoody UPF50',
                'thumbnail_url'    => null,
                'sku'              => 'TOP-HOOD-UPF-WHT',
                'units'            => 144,
                'revenue'          => 8064.00,
                'orders'           => 141,
                'aov'              => 57.19,
                'cogs'             => 16.50,
                'margin_pct'       => 70.5,
                'velocity'         => 5.14,
                'velocity_sparkline' => $spark(5.14),
                'label'            => 'hot',
                'sources'          => ['store', 'real', 'google'],
                'days_of_cover'    => 13.2,
                'views'            => 3200,
                'view_cvr'         => 0.044,
                'add_to_cart_rate' => 0.12,
                'top_campaigns'    => ['UV Protection – Summer'],
                'repeat_rate'      => 0.23,
            ],
            [
                'id'               => 44,
                'external_id'      => 'prod_01HWQA44',
                'name'             => 'Merino Scarf',
                'thumbnail_url'    => null,
                'sku'              => 'ACC-SCARF-MW-CRM',
                'units'            => 88,
                'revenue'          => 3344.00,
                'orders'           => 86,
                'aov'              => 38.88,
                'cogs'             => null,
                'margin_pct'       => null,
                'velocity'         => 3.14,
                'velocity_sparkline' => $spark(3.14),
                'label'            => null,
                'sources'          => ['store', 'real'],
                'days_of_cover'    => 17.2,
                'views'            => 1160,
                'view_cvr'         => 0.074,
                'add_to_cart_rate' => 0.17,
                'top_campaigns'    => [],
                'repeat_rate'      => null,
            ],
            [
                'id'               => 45,
                'external_id'      => 'prod_01HWQA45',
                'name'             => 'Performance Cap',
                'thumbnail_url'    => null,
                'sku'              => 'HAT-PERF-CAP-BLK',
                'units'            => 248,
                'revenue'          => 6448.00,
                'orders'           => 243,
                'aov'              => 26.53,
                'cogs'             => 6.00,
                'margin_pct'       => 76.9,
                'velocity'         => 8.86,
                'velocity_sparkline' => $spark(8.86),
                'label'            => null,
                'sources'          => ['store', 'real'],
                'days_of_cover'    => 20.8,
                'views'            => 3200,
                'view_cvr'         => 0.076,
                'add_to_cart_rate' => 0.22,
                'top_campaigns'    => [],
                'repeat_rate'      => 0.30,
            ],
            [
                'id'               => 46,
                'external_id'      => 'prod_01HWQA46',
                'name'             => 'Posture Correction Brace',
                'thumbnail_url'    => null,
                'sku'              => 'GEAR-PSTR-BRACE-MLT',
                'units'            => 62,
                'revenue'          => 1984.00,
                'orders'           => 61,
                'aov'              => 32.52,
                'cogs'             => 18.00,
                'margin_pct'       => 43.7,
                'velocity'         => 2.21,
                'velocity_sparkline' => $spark(2.21),
                'label'            => 'at_risk',
                'sources'          => ['store', 'real'],
                'days_of_cover'    => 16.3,
                'views'            => 980,
                'view_cvr'         => 0.062,
                'add_to_cart_rate' => 0.13,
                'top_campaigns'    => [],
                'repeat_rate'      => 0.06,
            ],
            [
                'id'               => 47,
                'external_id'      => 'prod_01HWQA47',
                'name'             => 'Tarp Shelter 3×3',
                'thumbnail_url'    => null,
                'sku'              => 'GEAR-TARP-3X3-GRN',
                'units'            => 14,
                'revenue'          => 1148.00,
                'orders'           => 14,
                'aov'              => 82.0,
                'cogs'             => null,
                'margin_pct'       => null,
                'velocity'         => 0.50,
                'velocity_sparkline' => $spark(0.50),
                'label'            => null,
                'sources'          => ['store', 'real'],
                'days_of_cover'    => 18.0,
                'views'            => 380,
                'view_cvr'         => 0.037,
                'add_to_cart_rate' => 0.08,
                'top_campaigns'    => [],
                'repeat_rate'      => null,
            ],
            [
                'id'               => 48,
                'external_id'      => 'prod_01HWQA48',
                'name'             => 'Climbing Helmet',
                'thumbnail_url'    => null,
                'sku'              => 'GEAR-CLMHMT-RED',
                'units'            => 32,
                'revenue'          => 2496.00,
                'orders'           => 31,
                'aov'              => 80.52,
                'cogs'             => 34.00,
                'margin_pct'       => 56.4,
                'velocity'         => 1.14,
                'velocity_sparkline' => $spark(1.14),
                'label'            => null,
                'sources'          => ['store', 'real'],
                'days_of_cover'    => 15.8,
                'views'            => 680,
                'view_cvr'         => 0.046,
                'add_to_cart_rate' => 0.10,
                'top_campaigns'    => [],
                'repeat_rate'      => null,
            ],
            [
                'id'               => 49,
                'external_id'      => 'prod_01HWQA49',
                'name'             => 'Cold Brew Tumbler 500ml',
                'thumbnail_url'    => null,
                'sku'              => 'ACC-TUMBLR-500-SLT',
                'units'            => 286,
                'revenue'          => 8008.00,
                'orders'           => 280,
                'aov'              => 28.60,
                'cogs'             => 8.50,
                'margin_pct'       => 69.7,
                'velocity'         => 10.21,
                'velocity_sparkline' => $spark(10.21),
                'label'            => 'hot',
                'sources'          => ['store', 'real'],
                'days_of_cover'    => 16.5,
                'views'            => 3840,
                'view_cvr'         => 0.073,
                'add_to_cart_rate' => 0.20,
                'top_campaigns'    => [],
                'repeat_rate'      => 0.28,
            ],
            [
                'id'               => 50,
                'external_id'      => 'prod_01HWQA50',
                'name'             => 'Titanium Spork',
                'thumbnail_url'    => null,
                'sku'              => 'GEAR-SPORK-TI-SLV',
                'units'            => 512,
                'revenue'          => 7168.00,
                'orders'           => 502,
                'aov'              => 14.28,
                'cogs'             => 3.80,
                'margin_pct'       => 72.9,
                'velocity'         => 18.29,
                'velocity_sparkline' => $spark(18.29),
                'label'            => null,
                'sources'          => ['store', 'real'],
                'days_of_cover'    => 67.9,
                'views'            => 6200,
                'view_cvr'         => 0.081,
                'add_to_cart_rate' => 0.24,
                'top_campaigns'    => [],
                'repeat_rate'      => 0.52,
            ],
        ];
    }
}
